steps:
- name: gcr.io/cloud-builders/docker
  id: Build
  args:
    - build
    - -t
    - gcr.io/$PROJECT_ID/${_SERVICE}:$COMMIT_SHA
    - -f
    - ${_DOCKERFILE}
    - ${_CONTEXT}
- name: 'gcr.io/cloud-builders/npm'
  dir: 'frontend'
  args: ['ci']

- name: 'gcr.io/cloud-builders/npm'
  dir: 'frontend'
  args: ['run','build']

- name: 'gcr.io/cloud-builders/npm'
  dir: 'frontend'
  entrypoint: 'bash'
  args:
    - -lc
    - |
      npm i -g firebase-tools
      firebase deploy --project ${PROJECT_ID} --only hosting,functions --non-interactive
images:
- gcr.io/$PROJECT_ID/${_SERVICE}:$COMMIT_SHA

substitutions:
  _FRONTEND_DIR: 'frontend'
options:
  logging: CLOUD_LOGGING_ONLY
