steps:
- name: gcr.io/cloud-builders/docker
  id: Build
  entrypoint: bash
  args:
    - -c
    - |
      set -euo pipefail

      IMAGE="gcr.io/$PROJECT_ID/${_SERVICE}:$COMMIT_SHA"
      TARGET_DOCKERFILE="${_DOCKERFILE:-Dockerfile}"
      TARGET_CONTEXT="${_CONTEXT:-.}"

      resolve_dockerfile() {
        local candidate="$1"
        if [ -f "$candidate" ]; then
          printf '%s' "$candidate"
          return 0
        fi
        if [ -d "$candidate" ] && [ -f "$candidate/Dockerfile" ]; then
          printf '%s' "$candidate/Dockerfile"
          return 0
        fi
        if [ -f "$candidate/Dockerfile" ]; then
          printf '%s' "$candidate/Dockerfile"
          return 0
        fi
        if [ -f "services/$candidate" ]; then
          printf '%s' "services/$candidate"
          return 0
        fi
        if [ -d "services/$candidate" ] && [ -f "services/$candidate/Dockerfile" ]; then
          printf '%s' "services/$candidate/Dockerfile"
          return 0
        fi
        if [[ "$candidate" == */Dockerfile ]]; then
          local base="${candidate%/Dockerfile}"
          if [ -d "services/$base" ] && [ -f "services/$base/Dockerfile" ]; then
            printf '%s' "services/$base/Dockerfile"
            return 0
          fi
        fi
        echo "Unable to resolve dockerfile path for '$candidate'" >&2
        exit 1
      }

      resolve_context() {
        local ctx="$1"
        if [ -d "$ctx" ]; then
          printf '%s' "$ctx"
          return 0
        fi
        if [ -d "services/$ctx" ]; then
          printf '%s' "services/$ctx"
          return 0
        fi
        echo "Unable to resolve docker build context '$ctx'" >&2
        exit 1
      }

      DOCKERFILE_PATH="$(resolve_dockerfile "$TARGET_DOCKERFILE")"
      CONTEXT_PATH="$(resolve_context "$TARGET_CONTEXT")"

      docker build -t "$IMAGE" -f "$DOCKERFILE_PATH" "$CONTEXT_PATH"
- name: 'gcr.io/cloud-builders/npm'
  dir: 'frontend'
  args: ['ci']

- name: 'gcr.io/cloud-builders/npm'
  dir: 'frontend'
  args: ['run','build']

- name: 'gcr.io/cloud-builders/npm'
  dir: 'frontend'
  entrypoint: 'bash'
  args:
    - -lc
    - |
      npm i -g firebase-tools
      firebase deploy --project ${PROJECT_ID} --only hosting,functions --non-interactive
images:
- gcr.io/$PROJECT_ID/${_SERVICE}:$COMMIT_SHA

substitutions:
  _FRONTEND_DIR: 'frontend'
options:
  logging: CLOUD_LOGGING_ONLY
