swagger: "2.0"
info:
  title: lit-caller-api
  version: v9
schemes: ["https"]

paths:
  /public/getFilterOptions:
    options:
      operationId: corsPublicGetFilterOptions
      x-google-backend:
        address: https://search-unified-<hash>-uc.a.run.app
        jwt_audience: https://search-unified-<hash>-uc.a.run.app
      responses:
        "204": { description: No Content }
    get:
      operationId: publicGetFilterOptions
      x-google-backend:
        address: https://search-unified-<hash>-uc.a.run.app
        jwt_audience: https://search-unified-<hash>-uc.a.run.app
      responses:
        "200": { description: OK }

  /public/searchCompanies:
    options:
      operationId: corsPublicSearchCompanies
      x-google-backend:
        address: https://search-unified-<hash>-uc.a.run.app
        jwt_audience: https://search-unified-<hash>-uc.a.run.app
      responses:
        "204": { description: No Content }
    post:
      operationId: publicSearchCompanies
      x-google-backend:
        address: https://search-unified-<hash>-uc.a.run.app
        jwt_audience: https://search-unified-<hash>-uc.a.run.app
      responses:
        "200": { description: OK }

  /crm/companies:
    options:
      operationId: corsCrmCompanies
      x-google-backend:
        address: https://crm-api-<hash>-uc.a.run.app
        jwt_audience: https://crm-api-<hash>-uc.a.run.app
      responses:
        "204": { description: No Content }
    post:
      operationId: crmCompaniesCreate
      x-google-backend:
        address: https://crm-api-<hash>-uc.a.run.app
        jwt_audience: https://crm-api-<hash>-uc.a.run.app
      responses:
        "200": { description: OK }

  /crm/companies/{id}:
    options:
      operationId: corsCrmCompanyGet
      x-google-backend:
        address: https://crm-api-<hash>-uc.a.run.app
        jwt_audience: https://crm-api-<hash>-uc.a.run.app
      responses:
        "204": { description: No Content }
    get:
      operationId: crmCompaniesGet
      x-google-backend:
        address: https://crm-api-<hash>-uc.a.run.app
        jwt_audience: https://crm-api-<hash>-uc.a.run.app
      responses:
        "200": { description: OK }

  /crm/contacts:
    options:
      operationId: corsCrmContacts
      x-google-backend:
        address: https://crm-api-<hash>-uc.a.run.app
        jwt_audience: https://crm-api-<hash>-uc.a.run.app
      responses:
        "204": { description: No Content }
    post:
      operationId: crmContactsCreate
      x-google-backend:
        address: https://crm-api-<hash>-uc.a.run.app
        jwt_audience: https://crm-api-<hash>-uc.a.run.app
      responses:
        "200": { description: OK }

  /crm/outreach:
    options:
      operationId: corsCrmOutreach
      x-google-backend:
        address: https://crm-api-<hash>-uc.a.run.app
        jwt_audience: https://crm-api-<hash>-uc.a.run.app
      responses:
        "204": { description: No Content }
    post:
      operationId: crmOutreachCreate
      x-google-backend:
        address: https://crm-api-<hash>-uc.a.run.app
        jwt_audience: https://crm-api-<hash>-uc.a.run.app
      responses:
        "200": { description: OK }

  /crm/feature-flags:
    options:
      operationId: corsCrmFeatureFlags
      x-google-backend:
        address: https://crm-api-<hash>-uc.a.run.app
        jwt_audience: https://crm-api-<hash>-uc.a.run.app
      responses:
        "204": { description: No Content }
    get:
      operationId: crmFeatureFlags
      x-google-backend:
        address: https://crm-api-<hash>-uc.a.run.app
        jwt_audience: https://crm-api-<hash>-uc.a.run.app
      responses:
        "200": { description: OK }

  /admin/audit:
    options:
      operationId: corsAdminAudit
      x-google-backend:
        address: https://crm-api-<hash>-uc.a.run.app
        jwt_audience: https://crm-api-<hash>-uc.a.run.app
      responses:
        "204": { description: No Content }
    get:
      operationId: adminAudit
      x-google-backend:
        address: https://crm-api-<hash>-uc.a.run.app
        jwt_audience: https://crm-api-<hash>-uc.a.run.app
      responses:
        "200": { description: OK }
