swagger: "2.0"
info:
  title: lit-caller-api
  version: v8
schemes: ["https"]

# NOTE: Host is managed by API Gateway; do not hardcode it in 'host:'.
# We set per-path backends below.

paths:
  /searchCompanies:
    post:
      operationId: searchCompanies
      x-google-backend:
        address: https://search-unified-187580267283.us-central1.run.app/searchCompanies
      responses:
        "200":
          description: OK
      security:
        - litProxyHeader: []   # secured route (keeps your header check)

  /getFilterOptions:
    post:
      operationId: getFilterOptions
      x-google-backend:
        address: https://search-unified-187580267283.us-central1.run.app/getFilterOptions
      responses:
        "200":
          description: OK
      security:
        - litProxyHeader: []   # secured route (keeps your header check)

  # Public browser-safe route — no security block
  /public/getFilterOptions:
    post:
      operationId: publicGetFilterOptions
      x-google-backend:
        address: https://search-unified-187580267283.us-central1.run.app/getFilterOptions
      responses:
        "200":
          description: OK

  # ==== NEW PUBLIC ROUTES (browser-safe; no security block) ====

  # CRM — outreach history (Campaigns service)
  /public/crm/outreach-history:
    post:
      operationId: crmOutreachHistory
      x-google-backend:
        address: https://campaigns-187580267283.us-central1.run.app/public/crm/outreach-history
      responses:
        "200":
          description: OK

  # CRM — persona generate (CRM Contacts service)
  /public/crm/persona/generate:
    post:
      operationId: crmPersonaGenerate
      x-google-backend:
        address: https://crm-contacts-187580267283.us-central1.run.app/public/crm/persona/generate
      responses:
        "200":
          description: OK

  # CRM — schedule followups (Campaigns service)
  /public/crm/followups/schedule:
    post:
      operationId: crmFollowupsSchedule
      x-google-backend:
        address: https://campaigns-187580267283.us-central1.run.app/public/crm/followups/schedule
      responses:
        "200":
          description: OK

  # Admin — import jobs (Admin Functions service)
  /public/admin/import-jobs:
    get:
      operationId: adminImportJobs
      x-google-backend:
        address: https://admin-functions-187580267283.us-central1.run.app/public/admin/import-jobs
      responses:
        "200":
          description: OK

  # Admin — audit logs (Admin Functions service)
  /public/admin/audit-logs:
    get:
      operationId: adminAuditLogs
      x-google-backend:
        address: https://admin-functions-187580267283.us-central1.run.app/public/admin/audit-logs
      responses:
        "200":
          description: OK

  # Admin — feature flags (Admin Functions service)
  /public/admin/feature-flags:
    get:
      operationId: adminFeatureFlags
      x-google-backend:
        address: https://admin-functions-187580267283.us-central1.run.app/public/admin/feature-flags
      responses:
        "200":
          description: OK

  # Widgets — Tariff Calculator (Widgets Tariff service)
  /public/widgets/tariff/calc:
    post:
      operationId: widgetsTariffCalc
      x-google-backend:
        address: https://widgets-tariff-187580267283.us-central1.run.app/public/widgets/tariff/calc
      responses:
        "200":
          description: OK

  # Widgets — Quote Generator (Widgets Quote service)
  /public/widgets/quote/generate:
    post:
      operationId: widgetsQuoteGenerate
      x-google-backend:
        address: https://widgets-quote-187580267283.us-central1.run.app/public/widgets/quote/generate
      responses:
        "200":
          description: OK

securityDefinitions:
  litProxyHeader:
    type: apiKey
    in: header
    name: x-lit-proxy-token
