// Dashboard "Signals" card. Surfaces top 3 unseen real signals
// generated by generate_lit_signals() (cron-driven, no fakes).
// Click CTA -> mark acted; X -> dismiss; render -> mark seen.

import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { Sparkles, ArrowRight, X, AlertCircle } from "lucide-react";
import {
  listSignals,
  markSignalSeen,
  dismissSignal,
  actOnSignal,
  type SignalRow,
  type SignalSeverity,
} from "@/lib/signals";

const SEVERITY_STYLES: Record<SignalSeverity, { dot: string; chip: string }> = {
  low: { dot: "bg-slate-300", chip: "bg-slate-100 text-slate-600" },
  medium: { dot: "bg-amber-400", chip: "bg-amber-50 text-amber-700" },
  high: { dot: "bg-orange-500", chip: "bg-orange-50 text-orange-700" },
  critical: { dot: "bg-rose-500", chip: "bg-rose-50 text-rose-700" },
};

export default function SignalsCard() {
  const [rows, setRows] = useState<SignalRow[] | null>(null);
  const [hiddenIds, setHiddenIds] = useState<Set<string>>(new Set());

  useEffect(() => {
    let cancelled = false;
    (async () => {
      const data = await listSignals({ limit: 3, statuses: ["new", "seen"] });
      if (cancelled) return;
      setRows(data);
      for (const r of data) {
        if (r.status === "new") void markSignalSeen(r.id);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  const visible = (rows ?? []).filter((r) => !hiddenIds.has(r.id));

  if (rows === null) {
    return (
      <div className="bg-white border border-slate-200 rounded-[14px] p-4 animate-pulse">
        <div className="h-4 w-32 bg-slate-100 rounded mb-3" />
        <div className="h-3 w-full bg-slate-100 rounded mb-2" />
        <div className="h-3 w-3/4 bg-slate-100 rounded" />
      </div>
    );
  }

  if (visible.length === 0) {
    return (
      <div
        className="bg-white border border-slate-200 rounded-[14px] p-4"
        style={{ boxShadow: "0 8px 30px rgba(15,23,42,0.06)" }}
      >
        <div className="flex items-center gap-2 mb-2">
          <Sparkles className="w-4 h-4 text-cyan-500" />
          <h3
            className="text-sm font-bold text-slate-900"
            style={{ fontFamily: "'Space Grotesk', sans-serif" }}
          >
            Signals
          </h3>
        </div>
        <p className="text-xs text-slate-500">
          You're caught up. New signals will appear as your accounts move.
        </p>
      </div>
    );
  }

  return (
    <div
      className="bg-white border border-slate-200 rounded-[14px]"
      style={{ boxShadow: "0 8px 30px rgba(15,23,42,0.06)" }}
    >
      <div className="flex items-center justify-between px-[18px] pt-4 pb-3 border-b border-slate-100">
        <div className="flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-cyan-500" />
          <h3
            className="text-sm font-bold text-slate-900"
            style={{ fontFamily: "'Space Grotesk', sans-serif" }}
          >
            Signals worth your attention
          </h3>
        </div>
        <span className="text-[11px] text-slate-400 uppercase tracking-wide">
          Top {visible.length}
        </span>
      </div>
      <ul className="divide-y divide-slate-100">
        {visible.map((s) => (
          <SignalRowItem
            key={s.id}
            signal={s}
            onDismiss={async () => {
              setHiddenIds((prev) => new Set(prev).add(s.id));
              await dismissSignal(s.id);
            }}
            onAct={async () => {
              setHiddenIds((prev) => new Set(prev).add(s.id));
              await actOnSignal(s.id);
            }}
          />
        ))}
      </ul>
    </div>
  );
}

function SignalRowItem({
  signal,
  onDismiss,
  onAct,
}: {
  signal: SignalRow;
  onDismiss: () => void;
  onAct: () => void;
}) {
  const style = SEVERITY_STYLES[signal.severity] ?? SEVERITY_STYLES.medium;
  const cta = signal.cta_url;
  return (
    <li className="px-[18px] py-3 flex items-start gap-3">
      <span className={`mt-1.5 inline-block w-2 h-2 rounded-full ${style.dot}`} />
      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2 mb-0.5">
          <p className="text-sm font-semibold text-slate-900 truncate">{signal.title}</p>
          <span
            className={`text-[10px] font-medium px-1.5 py-0.5 rounded ${style.chip} uppercase tracking-wide`}
          >
            {signal.severity}
          </span>
        </div>
        {signal.description ? (
          <p className="text-xs text-slate-500 leading-snug">{signal.description}</p>
        ) : null}
        {cta ? (
          <Link
            to={cta}
            onClick={onAct}
            className="inline-flex items-center gap-1 mt-1.5 text-xs font-semibold text-blue-600 hover:text-blue-800"
          >
            {signal.cta_label ?? "Open"} <ArrowRight className="w-3 h-3" />
          </Link>
        ) : null}
      </div>
      <button
        type="button"
        onClick={onDismiss}
        aria-label="Dismiss"
        className="text-slate-300 hover:text-slate-500"
      >
        <X className="w-4 h-4" />
      </button>
    </li>
  );
}

export function SignalsCardError({ message }: { message: string }) {
  return (
    <div className="bg-white border border-rose-200 rounded-[14px] p-4">
      <div className="flex items-center gap-2 text-rose-600">
        <AlertCircle className="w-4 h-4" />
        <span className="text-sm font-medium">Signals unavailable</span>
      </div>
      <p className="text-xs text-slate-500 mt-1">{message}</p>
    </div>
  );
}
