/**
 * Pulse Brief HTML renderers.
 *
 * Single source of truth for the styled brief HTML used in BOTH:
 *   - Email body (send-pulse-brief-email edge fn body_html)
 *   - Browser print export (Save-as-PDF via window.print)
 *
 * Two render modes:
 *   - 'email': 640px fixed-width branded shell with light-gray background.
 *     Inline styles only (no <link>), since most mail clients strip
 *     external CSS.
 *   - 'print': full Letter-portrait page with @page + @media print CSS
 *     so the browser's native print dialog produces a clean PDF without
 *     a Supabase Storage / signed-URL round-trip (which mis-served the
 *     file as text/plain).
 *
 * Both renderers consume the same PulseBrief shape from /pulse-brief.
 * The section + bullet helpers are intentionally tolerant — the upstream
 * API returns inconsistent shapes (string, {summary, bullets}, plain
 * array) and the renderer normalizes each section through `sectionText`
 * + `sectionAllBullets`.
 */

// ─── Types (mirror CDPResearch.tsx local declarations) ────────────────────

type Bullet = string | { text?: string; label?: string };

type SectionShape =
  | string
  | null
  | undefined
  | {
      summary?: string;
      bullets?: Bullet[];
      points?: Bullet[];
      items?: Bullet[];
    };

export type PulseBriefReport = {
  company_summary?: SectionShape;
  why_now?: SectionShape;
  sales_angle?: SectionShape;
  lit_verified_trade_data?: SectionShape;
  external_web_signals?: SectionShape;
  buying_signals?: SectionShape;
  risk_flags?: SectionShape;
  carrier_opportunities?: SectionShape;
  forwarder_displacement_opportunities?: SectionShape;
  lane_insights?: SectionShape;
  supplier_insights?: SectionShape;
  email_openers?: string[];
};

export type PulseBriefShape = {
  report?: PulseBriefReport | null;
} | null | undefined;

// ─── Helpers ──────────────────────────────────────────────────────────────

function escapeHtml(s: unknown): string {
  return String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function safeMultiline(s: unknown): string {
  return escapeHtml(s).replace(/\n/g, "<br/>");
}

export function sectionText(section: SectionShape): string {
  if (!section) return "";
  if (typeof section === "string") return section.trim();
  const summary = typeof section.summary === "string" ? section.summary.trim() : "";
  return summary;
}

export function sectionAllBullets(section: SectionShape): string[] {
  if (!section || typeof section === "string") return [];
  const list = section.bullets || section.points || section.items || [];
  return (list || [])
    .map((b) => (typeof b === "string" ? b : b?.text || b?.label || ""))
    .filter((s) => !!s.trim());
}

export function mergeText(a: SectionShape, b: SectionShape): string {
  const left = sectionText(a);
  const right = sectionText(b);
  if (left && right) return `${left}\n\n${right}`;
  return left || right;
}

// ─── EMAIL RENDERER ───────────────────────────────────────────────────────
// 640px fixed width, inline styles, gradient hero. Identical layout to the
// existing CDPResearch.reportToHtml output so the migration is invisible
// to recipients. Replaces the in-file reportToHtml callers.

export function renderPulseBriefEmailHtml(
  companyName: string,
  brief: PulseBriefShape,
): string {
  const r = brief?.report;

  const wrap = (children: string) => `<!DOCTYPE html>
<html lang="en">
<body style="margin:0;padding:0;background:#F1F5F9;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;color:#0F172A;line-height:1.55;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#F1F5F9;padding:24px 12px;">
    <tr><td align="center">
      <table role="presentation" width="640" cellpadding="0" cellspacing="0" style="max-width:640px;width:100%;background:#FFFFFF;border:1px solid #E2E8F0;border-radius:14px;overflow:hidden;">
        <tr><td style="padding:18px 22px;background:linear-gradient(135deg,#0B1736 0%,#102240 100%);color:#F8FAFC;">
          <div style="font-size:11px;font-weight:700;letter-spacing:0.12em;text-transform:uppercase;color:#00F0FF;">Pulse AI Brief</div>
          <div style="font-size:22px;font-weight:700;margin-top:4px;">${escapeHtml(companyName)}</div>
        </td></tr>
        ${children}
        <tr><td style="padding:14px 22px;background:#F8FAFC;font-size:11px;color:#64748B;">
          Generated by LIT Pulse AI · ${new Date().toLocaleDateString()}
        </td></tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`;

  if (!r) {
    return wrap(
      `<tr><td style="padding:22px;color:#64748B;font-size:13px;">Pulse AI brief has not been generated yet.</td></tr>`,
    );
  }

  const section = (label: string, body: string, accent = "#3B82F6") => {
    if (!body) return "";
    return `<tr><td style="padding:18px 22px;border-top:1px solid #F1F5F9;">
  <div style="display:inline-block;padding:3px 8px;border-radius:4px;background:${accent}15;color:${accent};font-size:10px;font-weight:700;letter-spacing:0.08em;text-transform:uppercase;margin-bottom:8px;">${escapeHtml(label)}</div>
  <div style="font-size:13px;line-height:1.65;color:#1E293B;">${safeMultiline(body)}</div>
</td></tr>`;
  };

  const bulletSection = (label: string, items: string[], accent = "#10B981") => {
    const filtered = items.filter(Boolean);
    if (!filtered.length) return "";
    const lis = filtered
      .map((b) => `<li style="margin-bottom:6px;">${safeMultiline(b)}</li>`)
      .join("");
    return `<tr><td style="padding:18px 22px;border-top:1px solid #F1F5F9;">
  <div style="display:inline-block;padding:3px 8px;border-radius:4px;background:${accent}15;color:${accent};font-size:10px;font-weight:700;letter-spacing:0.08em;text-transform:uppercase;margin-bottom:8px;">${escapeHtml(label)}</div>
  <ul style="margin:0;padding-left:20px;font-size:13px;line-height:1.65;color:#1E293B;">${lis}</ul>
</td></tr>`;
  };

  const opener =
    Array.isArray(r.email_openers) && r.email_openers.length ? r.email_openers[0] : null;

  const parts = [
    section("Executive summary", mergeText(r.company_summary, r.why_now)),
    section("Sales angle", sectionText(r.sales_angle), "#8B5CF6"),
    section("LIT verified trade data", sectionText(r.lit_verified_trade_data), "#0EA5E9"),
    section("External web signals", sectionText(r.external_web_signals), "#F59E0B"),
    bulletSection("Buying signals", sectionAllBullets(r.buying_signals), "#10B981"),
    bulletSection("Risk flags", sectionAllBullets(r.risk_flags), "#EF4444"),
    bulletSection("Carrier opportunities", sectionAllBullets(r.carrier_opportunities), "#3B82F6"),
    bulletSection(
      "Forwarder displacement",
      sectionAllBullets(r.forwarder_displacement_opportunities),
      "#6366F1",
    ),
    bulletSection("Lane insights", sectionAllBullets(r.lane_insights), "#0EA5E9"),
    bulletSection("Supplier insights", sectionAllBullets(r.supplier_insights), "#14B8A6"),
    opener
      ? `<tr><td style="padding:18px 22px;border-top:1px solid #F1F5F9;background:#F0F9FF;">
  <div style="display:inline-block;padding:3px 8px;border-radius:4px;background:#0EA5E915;color:#0EA5E9;font-size:10px;font-weight:700;letter-spacing:0.08em;text-transform:uppercase;margin-bottom:8px;">Suggested email opener</div>
  <div style="font-size:13px;line-height:1.65;color:#1E293B;font-style:italic;">${safeMultiline(opener)}</div>
</td></tr>`
      : "",
  ].filter(Boolean);

  return wrap(parts.join(""));
}

// ─── PRINT / PDF RENDERER ─────────────────────────────────────────────────
// Letter-portrait, full-width layout. Includes @page + @media print so the
// browser's native Save-as-PDF produces a clean export with page-break-safe
// section blocks. Same content as the email renderer, but laid out for a
// document rather than an inbox preview pane.

export function renderPulseBriefPrintHtml(
  companyName: string,
  brief: PulseBriefShape,
): string {
  const r = brief?.report;
  const generatedAt = new Date().toLocaleString();

  const section = (label: string, body: string, accent = "#3B82F6") => {
    if (!body) return "";
    return `<section class="block">
  <div class="eyebrow" style="--accent:${accent};">${escapeHtml(label)}</div>
  <div class="prose">${safeMultiline(body)}</div>
</section>`;
  };

  const bulletSection = (label: string, items: string[], accent = "#10B981") => {
    const filtered = items.filter(Boolean);
    if (!filtered.length) return "";
    const lis = filtered.map((b) => `<li>${safeMultiline(b)}</li>`).join("");
    return `<section class="block">
  <div class="eyebrow" style="--accent:${accent};">${escapeHtml(label)}</div>
  <ul class="prose">${lis}</ul>
</section>`;
  };

  let body: string;
  if (!r) {
    body = `<section class="block"><p class="prose" style="color:#64748b;">Pulse AI brief has not been generated yet.</p></section>`;
  } else {
    const opener =
      Array.isArray(r.email_openers) && r.email_openers.length ? r.email_openers[0] : null;
    const parts = [
      section("Executive summary", mergeText(r.company_summary, r.why_now)),
      section("Sales angle", sectionText(r.sales_angle), "#8B5CF6"),
      section("LIT verified trade data", sectionText(r.lit_verified_trade_data), "#0EA5E9"),
      section("External web signals", sectionText(r.external_web_signals), "#F59E0B"),
      bulletSection("Buying signals", sectionAllBullets(r.buying_signals), "#10B981"),
      bulletSection("Risk flags", sectionAllBullets(r.risk_flags), "#EF4444"),
      bulletSection("Carrier opportunities", sectionAllBullets(r.carrier_opportunities), "#3B82F6"),
      bulletSection(
        "Forwarder displacement",
        sectionAllBullets(r.forwarder_displacement_opportunities),
        "#6366F1",
      ),
      bulletSection("Lane insights", sectionAllBullets(r.lane_insights), "#0EA5E9"),
      bulletSection("Supplier insights", sectionAllBullets(r.supplier_insights), "#14B8A6"),
      opener
        ? `<section class="block opener">
  <div class="eyebrow" style="--accent:#0EA5E9;">Suggested email opener</div>
  <div class="prose" style="font-style:italic;">${safeMultiline(opener)}</div>
</section>`
        : "",
    ].filter(Boolean);
    body = parts.join("\n");
  }

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>${escapeHtml(companyName)} — Pulse AI Brief</title>
<style>
:root { color-scheme: light; --ink:#0f172a; --muted:#475569; --line:#e2e8f0; }
* { box-sizing: border-box; }
html, body { margin:0; padding:0; background:#fff; color:var(--ink);
  font-family: ui-sans-serif,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif;
  line-height: 1.55; }
body { padding: 32px 40px 48px; max-width: 880px; margin: 0 auto; }
.hero { background: linear-gradient(135deg,#0B1736 0%,#102240 100%); color:#F8FAFC;
  border-radius: 16px; padding: 24px 28px; margin-bottom: 22px; }
.hero .eyebrow { font-size:11px; font-weight:700; letter-spacing:0.14em;
  text-transform:uppercase; color:#00F0FF; margin-bottom: 6px; }
.hero h1 { margin: 0; font-size: 26px; letter-spacing:-0.01em; }
.hero .meta { color:#cbd5f5; font-size:12px; margin-top: 6px; }
.block { border-top: 1px solid var(--line); padding: 18px 0 6px; }
.block:first-of-type { border-top: none; padding-top: 0; }
.eyebrow { display:inline-block; padding: 3px 8px; border-radius: 4px;
  background: color-mix(in srgb, var(--accent) 15%, transparent);
  color: var(--accent); font-size: 10px; font-weight: 700;
  letter-spacing: 0.10em; text-transform: uppercase; margin-bottom: 10px; }
.prose { font-size: 14px; line-height: 1.6; color: var(--ink); white-space: pre-wrap; }
ul.prose { padding-left: 20px; margin: 0; }
ul.prose li { margin-bottom: 6px; }
.opener { background:#F0F9FF; border-radius: 10px; padding: 14px 18px; margin-top: 10px; }
footer { color: var(--muted); font-size: 11px; text-align: center; margin-top: 28px;
  padding-top: 14px; border-top: 1px solid var(--line); }
@page { size: Letter; margin: 0.5in; }
@media print {
  body { padding: 0; max-width: none; }
  .hero { background: #0B1736 !important; color:#F8FAFC !important; border-radius: 12px;
    -webkit-print-color-adjust: exact; print-color-adjust: exact; page-break-after: avoid; }
  .block { page-break-inside: avoid; break-inside: avoid; }
  .opener { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
}
</style>
</head>
<body>
<header class="hero">
  <div class="eyebrow">Pulse AI Brief</div>
  <h1>${escapeHtml(companyName)}</h1>
  <div class="meta">Logistics Intel · Generated ${escapeHtml(generatedAt)}</div>
</header>
${body}
<footer>Generated by LIT Pulse AI · logisticintel.com</footer>
</body>
</html>`;
}
