-- Port centroid seed for lit_geo_place_centroids (one-time, idempotent).
--
-- Geocodes the ~459 distinct ports referenced by
-- lit_company_port_lanes (OSM via photon.komoot.io, 2026-08-19) so the
-- company-profile map can draw port-level lanes.
--
-- Key format (must match frontend/src/api/portLanes.ts):
--   exit ports:  port:<lower exit_port>|<lower exit_port_country>
--   entry ports: port:<lower entry_port>
--
-- precision='failed' rows (junk buckets like "All Other X Ports",
-- "Panama Canal", numeric codes, or genuine geocode misses) carry NULL
-- coords and are ignored by consumers — seeded anyway so the batch job
-- and future re-runs know they were attempted.
--
-- 398 geocoded / 61 failed.

insert into public.lit_geo_place_centroids
  (place_key, city, region, country, lat, lng, "precision", source)
values
  ('port:27762|', '27762', NULL, NULL, NULL, NULL, 'failed', 'photon-port'),
  ('port:42876|', '42876', NULL, NULL, NULL, NULL, 'failed', 'photon-port'),
  ('port:57010|', '57010', NULL, NULL, NULL, NULL, 'failed', 'photon-port'),
  ('port:97130|mexico', '97130', NULL, 'Mexico', NULL, NULL, 'failed', 'photon-port'),
  ('port:aberdeen-hoquiam, wa', 'Aberdeen-Hoquiam', 'Washington', 'United States', 46.9743, -123.8623, 'city', 'photon-port'),
  ('port:acajutla|el salvador', 'Acajutla', NULL, 'El Salvador', 13.6166, -89.8289, 'city', 'photon-port'),
  ('port:adabiya|egypt', 'Adabiya', NULL, 'Egypt', 29.8963, 32.4565, 'city', 'photon-port'),
  ('port:adelaide|australia', 'Adelaide', NULL, 'Australia', -34.9282, 138.5999, 'city', 'photon-port'),
  ('port:admiralty bay|saint vincent and the grenadines', 'Admiralty Bay', NULL, 'Saint Vincent and the Grenadines', 13.0165, -61.2320, 'city', 'photon-port'),
  ('port:al basrah|iraq', 'Al Basrah', NULL, 'Iraq', 30.4952, 47.8091, 'city', 'photon-port'),
  ('port:al jubail|saudi arabia', 'Al Jubail', NULL, 'Saudi Arabia', 27.0464, 49.6083, 'city', 'photon-port'),
  ('port:algeciras|spain', 'Algeciras', NULL, 'Spain', 36.1312, -5.4474, 'city', 'photon-port'),
  ('port:all columbia amazon region ports|chile', 'All Columbia Amazon Region Ports', NULL, 'Chile', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other argentina ports|argentina', 'All Other Argentina Ports', NULL, 'Argentina', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other bahamas ports|the bahamas', 'All Other Bahamas Ports', NULL, 'The Bahamas', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other belgium ports|belgium', 'All Other Belgium Ports', NULL, 'Belgium', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other brazil ports north of recife|brazil', 'All Other Brazil Ports North Of Recife', NULL, 'Brazil', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other brazil ports south of recife|brazil', 'All Other Brazil Ports South Of Recife', NULL, 'Brazil', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other canada atlantic region ports|united states of america', 'All Other Canada Atlantic Region Ports', NULL, 'United States of America', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other chile ports|chile', 'All Other Chile Ports', NULL, 'Chile', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other china (taiwan) ports|taiwan', 'All Other China (Taiwan) Ports', NULL, 'Taiwan', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other colombian caribbean region ports|colombia', 'All Other Colombian Caribbean Region Ports', NULL, 'Colombia', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other costa rica caribbean region ports|chile', 'All Other Costa Rica Caribbean Region Ports', NULL, 'Chile', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other costa rica west coast region ports|costa rica', 'All Other Costa Rica West Coast Region Ports', NULL, 'Costa Rica', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other dominican republic ports|dominican republic', 'All Other Dominican Republic Ports', NULL, 'Dominican Republic', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other egypt mediterranean region ports|egypt', 'All Other Egypt Mediterranean Region Ports', NULL, 'Egypt', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other el salvador ports|el salvador', 'All Other El Salvador Ports', NULL, 'El Salvador', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other england south and east coast ports|united kingdom', 'All Other England South And East Coast Ports', NULL, 'United Kingdom', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other france atlantic region ports|france', 'All Other France Atlantic Region Ports', NULL, 'France', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other germany atlantic region ports|germany', 'All Other Germany Atlantic Region Ports', NULL, 'Germany', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other india east coast ports|india', 'All Other India East Coast Ports', NULL, 'India', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other india west coast ports|india', 'All Other India West Coast Ports', NULL, 'India', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other italy east coast ports|italy', 'All Other Italy East Coast Ports', NULL, 'Italy', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other japan ports|japan', 'All Other Japan Ports', NULL, 'Japan', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other jordan ports|jordan', 'All Other Jordan Ports', NULL, 'Jordan', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other madagascar ports|madagascar', 'All Other Madagascar Ports', NULL, 'Madagascar', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other malaysia ports|malaysia', 'All Other Malaysia Ports', NULL, 'Malaysia', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other malta ports|malta', 'All Other Malta Ports', NULL, 'Malta', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other mexico east coast region ports|spain', 'All Other Mexico East Coast Region Ports', NULL, 'Spain', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other netherlands ports|netherlands', 'All Other Netherlands Ports', NULL, 'Netherlands', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other oman ports|oman', 'All Other Oman Ports', NULL, 'Oman', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other pakistan ports|pakistan', 'All Other Pakistan Ports', NULL, 'Pakistan', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other panama west coast region ports|panama', 'All Other Panama West Coast Region Ports', NULL, 'Panama', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other peoples republic of china ports|china', 'All Other Peoples Republic Of China Ports', NULL, 'China', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other republic of south africa ports|south africa', 'All Other Republic Of South Africa Ports', NULL, 'South Africa', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other saudi arabia ports|saudi arabia', 'All Other Saudi Arabia Ports', NULL, 'Saudi Arabia', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other sierra leone ports|sierra leone', 'All Other Sierra Leone Ports', NULL, 'Sierra Leone', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other singapore ports|singapore', 'All Other Singapore Ports', NULL, 'Singapore', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other south korea ports|south korea', 'All Other South Korea Ports', NULL, 'South Korea', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other spain mediterranean region ports|spain', 'All Other Spain Mediterranean Region Ports', NULL, 'Spain', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other sri lanka ports|sri lanka', 'All Other Sri Lanka Ports', NULL, 'Sri Lanka', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other st. croix virgin islands|united states virgin islands', 'All Other St. Croix Virgin Islands', NULL, 'United States Virgin Islands', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other thailand ports|thailand', 'All Other Thailand Ports', NULL, 'Thailand', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other tunisia ports|tunisia', 'All Other Tunisia Ports', NULL, 'Tunisia', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other turkey black sea and sea of marmara port|turkey', 'All Other Turkey Black Sea And Sea Of Marmara Port', NULL, 'Turkey', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other turkey mediterranean region ports|turkey', 'All Other Turkey Mediterranean Region Ports', NULL, 'Turkey', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other united arab emirates ports|united arab emirates', 'All Other United Arab Emirates Ports', NULL, 'United Arab Emirates', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other uruguay ports|uruguay', 'All Other Uruguay Ports', NULL, 'Uruguay', NULL, NULL, 'failed', 'photon-port'),
  ('port:all other viet nam ports|vietnam', 'All Other Viet Nam Ports', NULL, 'Vietnam', NULL, NULL, 'failed', 'photon-port'),
  ('port:all ports in cambodia|cambodia', 'All Ports In Cambodia', NULL, 'Cambodia', NULL, NULL, 'failed', 'photon-port'),
  ('port:all united states outlying islands|united states of america', 'All United States Outlying Islands', NULL, 'United States of America', NULL, NULL, 'failed', 'photon-port'),
  ('port:anchorage, alaska', 'Anchorage', 'Alaska', 'United States', 61.2163, -149.8949, 'city', 'photon-port'),
  ('port:antofagasta|chile', 'Antofagasta', NULL, 'Chile', -23.6464, -70.3980, 'city', 'photon-port'),
  ('port:antwerp|belgium', 'Antwerp', NULL, 'Belgium', 51.2211, 4.3997, 'city', 'photon-port'),
  ('port:ashdod|israel', 'Ashdod', NULL, 'Israel', 31.7957, 34.6489, 'city', 'photon-port'),
  ('port:ashtabula/conneaut, ohio', 'Ashtabula/Conneaut', 'Ohio', 'United States', 41.9441, -80.5561, 'city', 'photon-port'),
  ('port:atlanta, ga.', 'Atlanta', 'Georgia', 'United States', 33.7387, -84.3590, 'city', 'photon-port'),
  ('port:attalea|turkey', 'Attalea', NULL, 'Turkey', 36.8866, 30.7030, 'city', 'photon-port'),
  ('port:auckland|new zealand', 'Auckland', NULL, 'New Zealand', -36.8521, 174.7632, 'city', 'photon-port'),
  ('port:bahia blanca|argentina', 'Bahia Blanca', NULL, 'Argentina', -38.7177, -62.2655, 'city', 'photon-port'),
  ('port:bahia de moin|costa rica', 'Bahia De Moin', NULL, 'Costa Rica', 10.0064, -83.1082, 'city', 'photon-port'),
  ('port:balboa|panama', 'Balboa', NULL, 'Panama', 8.9495, -79.5529, 'city', 'photon-port'),
  ('port:baltimore, md.', 'Baltimore', 'Maryland', 'United States', 39.3532, -76.6976, 'city', 'photon-port'),
  ('port:ban tha rua|thailand', 'Ban Tha Rua', NULL, 'Thailand', 13.7525, 100.4935, 'city', 'photon-port'),
  ('port:bangkok|thailand', 'Bangkok', NULL, 'Thailand', 13.7525, 100.4935, 'city', 'photon-port'),
  ('port:barao de teffe|brazil', 'Barao De Teffe', NULL, 'Brazil', -25.4299, -48.7125, 'city', 'photon-port'),
  ('port:barcelona|spain', 'Barcelona', NULL, 'Spain', 41.3826, 2.1771, 'city', 'photon-port'),
  ('port:barranquilla|colombia', 'Barranquilla', NULL, 'Colombia', 11.0102, -74.8232, 'city', 'photon-port'),
  ('port:baton rouge, la.', 'Baton Rouge', 'Louisiana', 'United States', 30.4378, -91.0859, 'city', 'photon-port'),
  ('port:bebington|united kingdom', 'Bebington', NULL, 'United Kingdom', 53.3504, -3.0056, 'city', 'photon-port'),
  ('port:beijiao|china', 'Beijiao', NULL, 'China', 22.8055, 113.2894, 'city', 'photon-port'),
  ('port:belfast|united kingdom', 'Belfast', NULL, 'United Kingdom', 54.5964, -5.9302, 'city', 'photon-port'),
  ('port:bilbao|spain', 'Bilbao', NULL, 'Spain', 43.2630, -2.9350, 'city', 'photon-port'),
  ('port:boston, mass', 'Boston', 'Massachusetts', 'United States', 42.3817, -71.0855, 'city', 'photon-port'),
  ('port:boston, mass.', 'Boston', 'Massachusetts', 'United States', 42.3817, -71.0855, 'city', 'photon-port'),
  ('port:brake|germany', 'Brake', NULL, 'Germany', 51.2247, 7.4471, 'city', 'photon-port'),
  ('port:bremen|germany', 'Bremen', NULL, 'Germany', 53.0758, 8.8072, 'city', 'photon-port'),
  ('port:bremerhaven|germany', 'Bremerhaven', NULL, 'Germany', 53.5505, 8.5852, 'city', 'photon-port'),
  ('port:bridgetown|barbados', 'Bridgetown', NULL, 'Barbados', 13.0978, -59.6184, 'city', 'photon-port'),
  ('port:brindisi|italy', 'Brindisi', NULL, 'Italy', 40.6359, 17.6885, 'city', 'photon-port'),
  ('port:brisbane|australia', 'Brisbane', NULL, 'Australia', -27.4690, 153.0235, 'city', 'photon-port'),
  ('port:brunswick, ga.', 'Brunswick', 'Georgia', 'United States', 31.2146, -81.4851, 'city', 'photon-port'),
  ('port:buenaventura|colombia', 'Buenaventura', NULL, 'Colombia', 3.8882, -77.0738, 'city', 'photon-port'),
  ('port:buenos aires|argentina', 'Buenos Aires', NULL, 'Argentina', -34.6096, -58.3888, 'city', 'photon-port'),
  ('port:cagliari|italy', 'Cagliari', NULL, 'Italy', 39.2172, 9.1133, 'city', 'photon-port'),
  ('port:caldera|costa rica', 'Caldera', NULL, 'Costa Rica', 9.9196, -84.6894, 'city', 'photon-port'),
  ('port:callao|peru', 'Callao', NULL, 'Peru', -12.0865, -77.2234, 'city', 'photon-port'),
  ('port:campana|argentina', 'Campana', NULL, 'Argentina', -34.1637, -58.9587, 'city', 'photon-port'),
  ('port:cape town|south africa', 'Cape Town', NULL, 'South Africa', -33.9288, 18.4172, 'city', 'photon-port'),
  ('port:carquinez strait, ca', 'Carquinez Strait', 'California', 'United States', 38.0493, -122.1731, 'city', 'photon-port'),
  ('port:cartagena|colombia', 'Cartagena', NULL, 'Colombia', 10.4266, -75.5442, 'city', 'photon-port'),
  ('port:castries|saint lucia', 'Castries', NULL, 'Saint Lucia', 14.0096, -60.9902, 'city', 'photon-port'),
  ('port:caucedo|dominican republic', 'Caucedo', NULL, 'Dominican Republic', 18.4433, -69.6489, 'city', 'photon-port'),
  ('port:charleston, s.c.', 'Charleston', 'South Carolina', 'United States', 32.7857, -79.9326, 'city', 'photon-port'),
  ('port:charleston, sc', 'Charleston', 'South Carolina', 'United States', 32.7857, -79.9326, 'city', 'photon-port'),
  ('port:charlotte amalie, st. thomas|united states virgin islands', 'Charlotte Amalie, St. Thomas', NULL, 'United States Virgin Islands', 18.3419, -64.9307, 'city', 'photon-port'),
  ('port:charlotte amalie, v.i.', 'Charlotte Amalie', 'United States Virgin Islands', 'United States', 18.3415, -64.9335, 'city', 'photon-port'),
  ('port:charlotte, n.c.', 'Charlotte', 'North Carolina', 'United States', 35.2253, -80.8921, 'city', 'photon-port'),
  ('port:chennai|india', 'Chennai', NULL, 'India', 13.0837, 80.2702, 'city', 'photon-port'),
  ('port:chester, pa.', 'Chester', 'Pennsylvania', 'United States', 40.0450, -75.5261, 'city', 'photon-port'),
  ('port:chicago, illinois', 'Chicago', 'Illinois', 'United States', 41.6916, -87.5343, 'city', 'photon-port'),
  ('port:chittagong|bangladesh', 'Chittagong', NULL, 'Bangladesh', 22.6839, 91.7891, 'city', 'photon-port'),
  ('port:chiwan|china', 'Chiwan', NULL, 'China', 22.4822, 113.8925, 'city', 'photon-port'),
  ('port:christiansted, st. croix|united states virgin islands', 'Christiansted, St. Croix', NULL, 'United States Virgin Islands', 17.7466, -64.7032, 'city', 'photon-port'),
  ('port:christiansted, v.i.', 'Christiansted', 'United States Virgin Islands', 'United States', 17.7444, -64.7076, 'city', 'photon-port'),
  ('port:chub cay|the bahamas', 'Chub Cay', NULL, 'The Bahamas', 25.4165, -77.8783, 'city', 'photon-port'),
  ('port:civitavecchia|italy', 'Civitavecchia', NULL, 'Italy', 42.0938, 11.7922, 'city', 'photon-port'),
  ('port:cleveland, ohio', 'Cleveland', 'Ohio', 'United States', 41.5134, -81.6000, 'city', 'photon-port'),
  ('port:cochin|india', 'Cochin', NULL, 'India', 9.9679, 76.2444, 'city', 'photon-port'),
  ('port:colombo harbor|sri lanka', 'Colombo Harbor', NULL, 'Sri Lanka', 6.9389, 79.8542, 'city', 'photon-port'),
  ('port:constantza|romania', 'Constantza', NULL, 'Romania', 44.1729, 28.6215, 'city', 'photon-port'),
  ('port:copenhagen|denmark', 'Copenhagen', NULL, 'Denmark', 55.6867, 12.5701, 'city', 'photon-port'),
  ('port:corpus christi, texas', 'Corpus Christi', 'Texas', 'United States', 27.7398, -97.4389, 'city', 'photon-port'),
  ('port:coryton|united kingdom', 'Coryton', NULL, 'United Kingdom', 51.5132, 0.5190, 'city', 'photon-port'),
  ('port:cozumel island|mexico', 'Cozumel Island', NULL, 'Mexico', 20.4321, -86.9207, 'city', 'photon-port'),
  ('port:cristobal|panama', 'Cristobal', NULL, 'Panama', 9.2686, -79.9120, 'city', 'photon-port'),
  ('port:da chan bay|china', 'Da Chan Bay', NULL, 'China', 22.5446, 114.0545, 'city', 'photon-port'),
  ('port:dagu/tanggu|china', 'Dagu/Tanggu', NULL, 'China', 39.0264, 117.6349, 'city', 'photon-port'),
  ('port:dalian|china', 'Dalian', NULL, 'China', 39.7403, 122.2558, 'city', 'photon-port'),
  ('port:derince burna|turkey', 'Derince Burna', NULL, 'Turkey', 40.7574, 29.8308, 'city', 'photon-port'),
  ('port:detroit, michigan', 'Detroit', 'Michigan', 'United States', 42.3641, -83.0885, 'city', 'photon-port'),
  ('port:dhl los angeles hub, ca', 'Dhl Los Angeles Hub', 'California', 'United States', 33.7405, -118.2723, 'city', 'photon-port'),
  ('port:dublin|ireland', 'Dublin', NULL, 'Ireland', 53.3494, -6.2606, 'city', 'photon-port'),
  ('port:dunkerque|france', 'Dunkerque', NULL, 'France', 51.0348, 2.3773, 'city', 'photon-port'),
  ('port:east london|south africa', 'East London', NULL, 'South Africa', -33.0192, 27.8999, 'city', 'photon-port'),
  ('port:el dekheila|egypt', 'El Dekheila', NULL, 'Egypt', 31.1315, 29.8032, 'city', 'photon-port'),
  ('port:ensenada|mexico', 'Ensenada', NULL, 'Mexico', 31.8659, -116.6030, 'city', 'photon-port'),
  ('port:everett, wa', 'Everett', 'Washington', 'United States', 47.9210, -122.2281, 'city', 'photon-port'),
  ('port:fairbanks, alaska', 'Fairbanks', 'Alaska', 'United States', 64.8378, -147.7167, 'city', 'photon-port'),
  ('port:felixstowe|united kingdom', 'Felixstowe', NULL, 'United Kingdom', 51.9643, 1.3290, 'city', 'photon-port'),
  ('port:fernandina, fla.', 'Fernandina', 'Florida', 'United States', 30.6712, -81.4630, 'city', 'photon-port'),
  ('port:fortaleza|brazil', 'Fortaleza', NULL, 'Brazil', -3.7305, -38.5218, 'city', 'photon-port'),
  ('port:fos sur mer|france', 'Fos Sur Mer', NULL, 'France', 43.4381, 4.9456, 'city', 'photon-port'),
  ('port:freeport, grand bahama island|the bahamas', 'Freeport, Grand Bahama Island', NULL, 'The Bahamas', 26.5357, -78.6954, 'city', 'photon-port'),
  ('port:freeport, ireland island|united kingdom', 'Freeport, Ireland Island', NULL, 'United Kingdom', 55.2858, -6.1829, 'city', 'photon-port'),
  ('port:freeport, texas', 'Freeport', 'Texas', 'United States', 28.9497, -95.3461, 'city', 'photon-port'),
  ('port:fukuyama|japan', 'Fukuyama', NULL, 'Japan', 34.4857, 133.3623, 'city', 'photon-port'),
  ('port:funchal|portugal', 'Funchal', NULL, 'Portugal', 32.6496, -16.9087, 'city', 'photon-port'),
  ('port:fuqing|china', 'Fuqing', NULL, 'China', 25.7237, 119.3795, 'city', 'photon-port'),
  ('port:fuzhou|china', 'Fuzhou', NULL, 'China', 26.0775, 119.2918, 'city', 'photon-port'),
  ('port:gabes|tunisia', 'Gabes', NULL, 'Tunisia', 33.8878, 10.1004, 'city', 'photon-port'),
  ('port:galveston, texas', 'Galveston', 'Texas', 'United States', 29.4041, -95.0364, 'city', 'photon-port'),
  ('port:gand|belgium', 'Gand', NULL, 'Belgium', 51.0538, 3.7250, 'city', 'photon-port'),
  ('port:gdansk|poland', 'Gdansk', NULL, 'Poland', 54.3483, 18.6540, 'city', 'photon-port'),
  ('port:gdynia|poland', 'Gdynia', NULL, 'Poland', 54.5233, 18.6040, 'city', 'photon-port'),
  ('port:genova|italy', 'Genova', NULL, 'Italy', 44.4073, 8.9339, 'city', 'photon-port'),
  ('port:ghemlik|turkey', 'Ghemlik', NULL, 'Turkey', 40.4302, 29.1571, 'city', 'photon-port'),
  ('port:gioia tauro|italy', 'Gioia Tauro', NULL, 'Italy', 38.4240, 15.8990, 'city', 'photon-port'),
  ('port:golfo de palmas|italy', 'Golfo De Palmas', NULL, 'Italy', 39.0353, 8.4118, 'city', 'photon-port'),
  ('port:golovasi terminal|turkey', 'Golovasi Terminal', NULL, 'Turkey', 37.0289, 35.8124, 'city', 'photon-port'),
  ('port:gooch island, bc|canada', 'Gooch Island, Bc', NULL, 'Canada', 49.2609, -123.1140, 'city', 'photon-port'),
  ('port:gothenburg|sweden', 'Gothenburg', NULL, 'Sweden', 57.7072, 11.9670, 'city', 'photon-port'),
  ('port:gramercy, la.', 'Gramercy', 'Louisiana', 'United States', 30.0474, -90.6898, 'city', 'photon-port'),
  ('port:grangemouth|united kingdom', 'Grangemouth', NULL, 'United Kingdom', 56.0189, -3.7230, 'city', 'photon-port'),
  ('port:great abaco island|the bahamas', 'Great Abaco Island', NULL, 'The Bahamas', 26.5383, -77.0610, 'city', 'photon-port'),
  ('port:greenhithe|united kingdom', 'Greenhithe', NULL, 'United Kingdom', 51.4507, 0.2818, 'city', 'photon-port'),
  ('port:greenock|united kingdom', 'Greenock', NULL, 'United Kingdom', 55.9473, -4.7565, 'city', 'photon-port'),
  ('port:guam island|guam', 'Guam Island', NULL, 'Guam', 13.4443, 144.6586, 'city', 'photon-port'),
  ('port:guangzhou|china', 'Guangzhou', NULL, 'China', 23.1288, 113.2590, 'city', 'photon-port'),
  ('port:guayaquil|ecuador', 'Guayaquil', NULL, 'Ecuador', -2.1901, -79.8869, 'city', 'photon-port'),
  ('port:gulf of mexico|united states of america', 'Gulf Of Mexico', NULL, 'United States of America', NULL, NULL, 'failed', 'photon-port'),
  ('port:gulfport, miss.', 'Gulfport', 'Mississippi', 'United States', 30.4225, -89.0912, 'city', 'photon-port'),
  ('port:hai phong|vietnam', 'Hai Phong', NULL, 'Vietnam', 20.8831, 106.6790, 'city', 'photon-port'),
  ('port:haifa|israel', 'Haifa', NULL, 'Israel', 32.8191, 34.9984, 'city', 'photon-port'),
  ('port:haikou|china', 'Haikou', NULL, 'China', 20.0462, 110.1957, 'city', 'photon-port'),
  ('port:hakata|japan', 'Hakata', NULL, 'Japan', 33.5900, 130.4204, 'city', 'photon-port'),
  ('port:haldia|india', 'Haldia', NULL, 'India', 22.0281, 88.0633, 'city', 'photon-port'),
  ('port:halifax, ns|canada', 'Halifax, Ns', NULL, 'Canada', 44.6486, -63.5859, 'city', 'photon-port'),
  ('port:hamilton|bermuda', 'Hamilton', NULL, 'Bermuda', 32.2943, -64.7853, 'city', 'photon-port'),
  ('port:hankow|china', 'Hankow', NULL, 'China', 30.6217, 114.2494, 'city', 'photon-port'),
  ('port:harburg|germany', 'Harburg', NULL, 'Germany', 53.4557, 9.9918, 'city', 'photon-port'),
  ('port:hazira|india', 'Hazira', NULL, 'India', 21.0956, 72.6466, 'city', 'photon-port'),
  ('port:helsingborg|sweden', 'Helsingborg', NULL, 'Sweden', 56.0442, 12.7037, 'city', 'photon-port'),
  ('port:helsingfors|finland', 'Helsingfors', NULL, 'Finland', 60.1666, 24.9435, 'city', 'photon-port'),
  ('port:high seas (outside u.s. territorial waters)|united states of america', 'High Seas (Outside U.S. Territorial Waters)', NULL, 'United States of America', NULL, NULL, 'failed', 'photon-port'),
  ('port:high seas, north atlantic (maine to cape hatteras)|united states of america', 'High Seas, North Atlantic (Maine To Cape Hatteras)', NULL, 'United States of America', NULL, NULL, 'failed', 'photon-port'),
  ('port:high seas, north pacific (alaska, washington, oregon)|united states of america', 'High Seas, North Pacific (Alaska, Washington, Oregon)', NULL, 'United States of America', NULL, NULL, 'failed', 'photon-port'),
  ('port:high seas, south atlantic (cape hatteras to florida)|united states of america', 'High Seas, South Atlantic (Cape Hatteras To Florida)', NULL, 'United States of America', NULL, NULL, 'failed', 'photon-port'),
  ('port:hitachi ko|japan', 'Hitachi Ko', NULL, 'Japan', 36.5991, 140.6505, 'city', 'photon-port'),
  ('port:hong kong|hong kong s.a.r.', 'Hong Kong', NULL, 'Hong Kong S.A.R.', 22.3193, 114.1694, 'city', 'photon-port'),
  ('port:honolulu, hawaii', 'Honolulu', 'Hawaii', 'United States', 21.3153, -157.8620, 'city', 'photon-port'),
  ('port:houston, texas', 'Houston', 'Texas', 'United States', 29.7536, -95.3597, 'city', 'photon-port'),
  ('port:huangpu|china', 'Huangpu', NULL, 'China', 31.2336, 121.4799, 'city', 'photon-port'),
  ('port:huelva|spain', 'Huelva', NULL, 'Spain', 37.2576, -6.9485, 'city', 'photon-port'),
  ('port:huizhou|china', 'Huizhou', NULL, 'China', 23.1125, 114.4127, 'city', 'photon-port'),
  ('port:imbituba|brazil', 'Imbituba', NULL, 'Brazil', -28.2418, -48.6643, 'city', 'photon-port'),
  ('port:immingham|united kingdom', 'Immingham', NULL, 'United Kingdom', 53.6160, -0.2137, 'city', 'photon-port'),
  ('port:isdemir|turkey', 'Isdemir', NULL, 'Turkey', 36.5902, 36.1710, 'city', 'photon-port'),
  ('port:istanbul|turkey', 'Istanbul', NULL, 'Turkey', 41.0064, 28.9759, 'city', 'photon-port'),
  ('port:itajay|brazil', 'Itajay', NULL, 'Brazil', -26.9047, -48.6553, 'city', 'photon-port'),
  ('port:izmir|turkey', 'Izmir', NULL, 'Turkey', 38.4193, 27.1285, 'city', 'photon-port'),
  ('port:jackman, me', 'Jackman', 'Maine', 'United States', 45.6238, -70.2540, 'city', 'photon-port'),
  ('port:jacksonville, fla', 'Jacksonville', 'Florida', 'United States', 30.3647, -81.7041, 'city', 'photon-port'),
  ('port:jacksonville, fla.', 'Jacksonville', 'Florida', 'United States', 30.3647, -81.7041, 'city', 'photon-port'),
  ('port:jawaharlal nehru|india', 'Jawaharlal Nehru', NULL, 'India', 18.9450, 72.9494, 'city', 'photon-port'),
  ('port:jebel ali|united arab emirates', 'Jebel Ali', NULL, 'United Arab Emirates', 24.9986, 55.0724, 'city', 'photon-port'),
  ('port:jiangyin|china', 'Jiangyin', NULL, 'China', 31.9216, 120.2809, 'city', 'photon-port'),
  ('port:jiddah|saudi arabia', 'Jiddah', NULL, 'Saudi Arabia', 21.5504, 39.1742, 'city', 'photon-port'),
  ('port:jinsen|south korea', 'Jinsen', NULL, 'South Korea', 37.4560, 126.7052, 'city', 'photon-port'),
  ('port:jiuzhou|china', 'Jiuzhou', NULL, 'China', 22.2737, 113.5721, 'city', 'photon-port'),
  ('port:kao hsiung|taiwan', 'Kao Hsiung', NULL, 'Taiwan', 22.6203, 120.3120, 'city', 'photon-port'),
  ('port:kaohsiung|taiwan', 'Kaohsiung', NULL, 'Taiwan', 22.6203, 120.3120, 'city', 'photon-port'),
  ('port:karachi harbor|pakistan', 'Karachi Harbor', NULL, 'Pakistan', 24.8547, 67.0207, 'city', 'photon-port'),
  ('port:kawasaki|japan', 'Kawasaki', NULL, 'Japan', 35.5307, 139.7038, 'city', 'photon-port'),
  ('port:keelung|taiwan', 'Keelung', NULL, 'Taiwan', 25.1317, 121.7447, 'city', 'photon-port'),
  ('port:kilindini|kenya', 'Kilindini', NULL, 'Kenya', -4.0505, 39.6672, 'city', 'photon-port'),
  ('port:king abdul aziz port|saudi arabia', 'King Abdul Aziz Port', NULL, 'Saudi Arabia', 26.4368, 50.1040, 'city', 'photon-port'),
  ('port:klaipeda|lithuania', 'Klaipeda', NULL, 'Lithuania', 55.7128, 21.1350, 'city', 'photon-port'),
  ('port:kobe|japan', 'Kobe', NULL, 'Japan', 34.6932, 135.1944, 'city', 'photon-port'),
  ('port:kolkata|india', 'Kolkata', NULL, 'India', 22.5726, 88.3639, 'city', 'photon-port'),
  ('port:kotka|finland', 'Kotka', NULL, 'Finland', 60.4673, 26.9459, 'city', 'photon-port'),
  ('port:kunson|south korea', 'Kunson', NULL, 'South Korea', 35.9680, 126.7369, 'city', 'photon-port'),
  ('port:kwangyang|south korea', 'Kwangyang', NULL, 'South Korea', 34.9406, 127.6960, 'city', 'photon-port'),
  ('port:la fitteau|haiti', 'La Fitteau', NULL, 'Haiti', 18.5473, -72.3396, 'city', 'photon-port'),
  ('port:la guaira|venezuela', 'La Guaira', NULL, 'Venezuela', 10.6000, -66.9296, 'city', 'photon-port'),
  ('port:la spezia|italy', 'La Spezia', NULL, 'Italy', 44.2384, 9.6912, 'city', 'photon-port'),
  ('port:laem chabang|thailand', 'Laem Chabang', NULL, 'Thailand', 13.0879, 100.9257, 'city', 'photon-port'),
  ('port:lake charles, la.', 'Lake Charles', 'Louisiana', 'United States', 30.1949, -93.2484, 'city', 'photon-port'),
  ('port:las salinas|chile', 'Las Salinas', NULL, 'Chile', -33.0245, -71.5518, 'city', 'photon-port'),
  ('port:lazaro cardenas|mexico', 'Lazaro Cardenas', NULL, 'Mexico', 17.9595, -102.1987, 'city', 'photon-port'),
  ('port:le havre|france', 'Le Havre', NULL, 'France', 49.4939, 0.1080, 'city', 'photon-port'),
  ('port:lianyungang|china', 'Lianyungang', NULL, 'China', 34.5933, 119.2172, 'city', 'photon-port'),
  ('port:lisbon|portugal', 'Lisbon', NULL, 'Portugal', 38.7078, -9.1366, 'city', 'photon-port'),
  ('port:liverpool|united kingdom', 'Liverpool', NULL, 'United Kingdom', 53.3933, -2.9166, 'city', 'photon-port'),
  ('port:livorno|italy', 'Livorno', NULL, 'Italy', 42.7902, 10.3402, 'city', 'photon-port'),
  ('port:londonderry|united kingdom', 'Londonderry', NULL, 'United Kingdom', 54.9808, -6.8845, 'city', 'photon-port'),
  ('port:long beach, ca', 'Long Beach', 'California', 'United States', 33.7542, -118.2165, 'city', 'photon-port'),
  ('port:long beach, calif', 'Long Beach', 'California', 'United States', 33.7542, -118.2165, 'city', 'photon-port'),
  ('port:los angeles, ca', 'Los Angeles', 'California', 'United States', 33.7405, -118.2723, 'city', 'photon-port'),
  ('port:los angeles, calif', 'Los Angeles', 'California', 'United States', 33.7405, -118.2723, 'city', 'photon-port'),
  ('port:lysaker|norway', 'Lysaker', NULL, 'Norway', 59.9134, 10.6370, 'city', 'photon-port'),
  ('port:malaga|spain', 'Malaga', NULL, 'Spain', 36.7960, -4.5474, 'city', 'photon-port'),
  ('port:manila|philippines', 'Manila', NULL, 'Philippines', 14.5904, 120.9804, 'city', 'photon-port'),
  ('port:marina di carrara|italy', 'Marina Di Carrara', NULL, 'Italy', 44.0377, 10.0455, 'city', 'photon-port'),
  ('port:marsaxlokk|malta', 'Marsaxlokk', NULL, 'Malta', 35.8418, 14.5448, 'city', 'photon-port'),
  ('port:marseille|france', 'Marseille', NULL, 'France', 43.2964, 5.3778, 'city', 'photon-port'),
  ('port:masan|south korea', 'Masan', NULL, 'South Korea', 35.2364, 128.5767, 'city', 'photon-port'),
  ('port:memphis, tenn.', 'Memphis', 'Tennessee', 'United States', 35.0492, -89.8067, 'city', 'photon-port'),
  ('port:mersin|turkey', 'Mersin', NULL, 'Turkey', 36.7978, 34.6298, 'city', 'photon-port'),
  ('port:miami, florida', 'Miami', 'Florida', 'United States', 25.7708, -80.2939, 'city', 'photon-port'),
  ('port:military–port kelang|malaysia', 'Military–Port Kelang', NULL, 'Malaysia', 2.9996, 101.3914, 'city', 'photon-port'),
  ('port:military|china', 'Military', NULL, 'China', NULL, NULL, 'failed', 'photon-port'),
  ('port:mina dumyat|egypt', 'Mina Dumyat', NULL, 'Egypt', 31.4167, 31.8214, 'city', 'photon-port'),
  ('port:mina raysut|oman', 'Mina Raysut', NULL, 'Oman', 17.0175, 54.1011, 'city', 'photon-port'),
  ('port:mina zayed|united arab emirates', 'Mina Zayed', NULL, 'United Arab Emirates', 24.5280, 54.3761, 'city', 'photon-port'),
  ('port:minneapolis-st. paul, mn', 'Minneapolis-St. Paul', 'Minnesota', 'United States', 44.8780, -93.2209, 'city', 'photon-port'),
  ('port:misaki|japan', 'Misaki', NULL, 'Japan', 34.3014, 135.1464, 'city', 'photon-port'),
  ('port:mizushima|japan', 'Mizushima', NULL, 'Japan', 34.5851, 133.7720, 'city', 'photon-port'),
  ('port:mobile, ala.', 'Mobile', 'Alabama', 'United States', 30.6933, -88.0318, 'city', 'photon-port'),
  ('port:mokpo|south korea', 'Mokpo', NULL, 'South Korea', 34.7903, 126.3848, 'city', 'photon-port'),
  ('port:monfalcone|italy', 'Monfalcone', NULL, 'Italy', 45.8049, 13.5331, 'city', 'photon-port'),
  ('port:montevideo|uruguay', 'Montevideo', NULL, 'Uruguay', -34.9059, -56.1913, 'city', 'photon-port'),
  ('port:montoir|france', 'Montoir', NULL, 'France', 47.3286, -2.1543, 'city', 'photon-port'),
  ('port:montreal, que|canada', 'Montreal, Que', NULL, 'Canada', 45.5032, -73.5698, 'city', 'photon-port'),
  ('port:morgan city, la.', 'Morgan City', 'Louisiana', 'United States', 29.6994, -91.2068, 'city', 'photon-port'),
  ('port:mosel|germany', 'Mosel', NULL, 'Germany', 50.3533, 7.5944, 'city', 'photon-port'),
  ('port:mozambique island|mozambique', 'Mozambique Island', NULL, 'Mozambique', -15.0378, 40.7321, 'city', 'photon-port'),
  ('port:mumbai|india', 'Mumbai', NULL, 'India', 19.0550, 72.8692, 'city', 'photon-port'),
  ('port:mundra|india', 'Mundra', NULL, 'India', 22.8393, 69.7249, 'city', 'photon-port'),
  ('port:nacala|mozambique', 'Nacala', NULL, 'Mozambique', -14.5583, 40.6864, 'city', 'photon-port'),
  ('port:nagoya ko|japan', 'Nagoya Ko', NULL, 'Japan', 35.1851, 136.8998, 'city', 'photon-port'),
  ('port:nan ching|china', 'Nan Ching', NULL, 'China', 32.0438, 118.7789, 'city', 'photon-port'),
  ('port:nansha|china', 'Nansha', NULL, 'China', 22.8044, 113.5198, 'city', 'photon-port'),
  ('port:nantong|china', 'Nantong', NULL, 'China', 31.9828, 120.8905, 'city', 'photon-port'),
  ('port:napier|new zealand', 'Napier', NULL, 'New Zealand', -39.4902, 176.9178, 'city', 'photon-port'),
  ('port:napoli|italy', 'Napoli', NULL, 'Italy', 40.8359, 14.2488, 'city', 'photon-port'),
  ('port:nassau, new providence island|the bahamas', 'Nassau, New Providence Island', NULL, 'The Bahamas', 25.0782, -77.3383, 'city', 'photon-port'),
  ('port:navegantes|brazil', 'Navegantes', NULL, 'Brazil', -26.8899, -48.6496, 'city', 'photon-port'),
  ('port:nemrut bay|turkey', 'Nemrut Bay', NULL, 'Turkey', 38.8034, 26.9714, 'city', 'photon-port'),
  ('port:new haven, conn.', 'New Haven', 'Connecticut', 'United States', 41.3086, -72.8961, 'city', 'photon-port'),
  ('port:new orleans, la.', 'New Orleans', 'Louisiana', 'United States', 29.9127, -90.0184, 'city', 'photon-port'),
  ('port:new tuticorin|india', 'New Tuticorin', NULL, 'India', 8.8457, 77.9938, 'city', 'photon-port'),
  ('port:new westminster, bc|canada', 'New Westminster, Bc', NULL, 'Canada', 49.2068, -122.9109, 'city', 'photon-port'),
  ('port:new york, n.y.', 'New York', 'New York', 'United States', 40.7506, -73.9688, 'city', 'photon-port'),
  ('port:new york, ny', 'New York', 'New York', 'United States', 40.7506, -73.9688, 'city', 'photon-port'),
  ('port:new york/newark area, newark, nj', 'Newark', 'New Jersey', 'United States', 40.6923, -74.1439, 'city', 'photon-port'),
  ('port:newark, nj', 'Newark', 'New Jersey', 'United States', 40.6923, -74.1439, 'city', 'photon-port'),
  ('port:ning bo|china', 'Ning Bo', NULL, 'China', 29.8622, 121.6204, 'city', 'photon-port'),
  ('port:norfolk, va', 'Norfolk', 'Virginia', 'United States', 36.9148, -76.2477, 'city', 'photon-port'),
  ('port:norfolk, va.', 'Norfolk', 'Virginia', 'United States', 36.9148, -76.2477, 'city', 'photon-port'),
  ('port:oakland, ca', 'Oakland', 'California', 'United States', 37.7997, -122.2166, 'city', 'photon-port'),
  ('port:ocean cay|the bahamas', 'Ocean Cay', NULL, 'The Bahamas', 25.7033, -79.2733, 'city', 'photon-port'),
  ('port:oporto|portugal', 'Oporto', NULL, 'Portugal', 41.1502, -8.6103, 'city', 'photon-port'),
  ('port:oxelosund|sweden', 'Oxelosund', NULL, 'Sweden', 58.6700, 17.1041, 'city', 'photon-port'),
  ('port:paarden baai|aruba', 'Paarden Baai', NULL, 'Aruba', 12.5150, -70.0358, 'city', 'photon-port'),
  ('port:pago pago harbor|american samoa', 'Pago Pago Harbor', NULL, 'American Samoa', -14.2740, -170.7046, 'city', 'photon-port'),
  ('port:panama canal|panama', 'Panama Canal', NULL, 'Panama', NULL, NULL, 'failed', 'photon-port'),
  ('port:panama city, fla.', 'Panama City', 'Florida', 'United States', 30.1775, -85.6833, 'city', 'photon-port'),
  ('port:pasir gudang|malaysia', 'Pasir Gudang', NULL, 'Malaysia', 1.4953, 103.9207, 'city', 'photon-port'),
  ('port:peruvian whaling grounds|peru', 'Peruvian Whaling Grounds', NULL, 'Peru', NULL, NULL, 'failed', 'photon-port'),
  ('port:philadelphia, pa.', 'Philadelphia', 'Pennsylvania', 'United States', 39.9777, -75.1740, 'city', 'photon-port'),
  ('port:philipsborough|sint maarten', 'Philipsborough', NULL, 'Sint Maarten', 18.0296, -63.0458, 'city', 'photon-port'),
  ('port:pinang|malaysia', 'Pinang', NULL, 'Malaysia', 5.4065, 100.2559, 'city', 'photon-port'),
  ('port:pipavav|india', 'Pipavav', NULL, 'India', 20.9389, 71.4770, 'city', 'photon-port'),
  ('port:piraeus|greece', 'Piraeus', NULL, 'Greece', 37.9432, 23.6471, 'city', 'photon-port'),
  ('port:point lisas|trinidad and tobago', 'Point Lisas', NULL, 'Trinidad and Tobago', 10.3748, -61.4841, 'city', 'photon-port'),
  ('port:pointe a pitre|guadeloupe', 'Pointe A Pitre', NULL, 'Guadeloupe', 16.2415, -61.5328, 'city', 'photon-port'),
  ('port:ponce, puerto rico', 'Ponce', 'Puerto Rico', 'United States', 18.0668, -66.6140, 'city', 'photon-port'),
  ('port:port angeles, wash.', 'Port Angeles', 'Washington', 'United States', 48.1181, -123.4307, 'city', 'photon-port'),
  ('port:port au prince|haiti', 'Port Au Prince', NULL, 'Haiti', 18.5473, -72.3396, 'city', 'photon-port'),
  ('port:port bustamante|jamaica', 'Port Bustamante', NULL, 'Jamaica', 17.9712, -76.7928, 'city', 'photon-port'),
  ('port:port canaveral, fla.', 'Port Canaveral', 'Florida', 'United States', 28.4161, -80.6078, 'city', 'photon-port'),
  ('port:port chalmers|new zealand', 'Port Chalmers', NULL, 'New Zealand', -45.8151, 170.6223, 'city', 'photon-port'),
  ('port:port do pecem|brazil', 'Port Do Pecem', NULL, 'Brazil', -3.5856, -38.8752, 'city', 'photon-port'),
  ('port:port elizabeth|south africa', 'Port Elizabeth', NULL, 'South Africa', -33.9580, 25.5999, 'city', 'photon-port'),
  ('port:port hueneme, ca', 'Port Hueneme', 'California', 'United States', 34.1478, -119.1952, 'city', 'photon-port'),
  ('port:port itapoa|brazil', 'Port Itapoa', NULL, 'Brazil', -26.1791, -48.6075, 'city', 'photon-port'),
  ('port:port klang|malaysia', 'Port Klang', NULL, 'Malaysia', 2.9996, 101.3914, 'city', 'photon-port'),
  ('port:port lavaca, texas', 'Port Lavaca', 'Texas', 'United States', 28.6333, -96.6284, 'city', 'photon-port'),
  ('port:port lyttelton|new zealand', 'Port Lyttelton', NULL, 'New Zealand', -43.6025, 172.7206, 'city', 'photon-port'),
  ('port:port manatee, fla.', 'Port Manatee', 'Florida', 'United States', 27.6336, -82.5615, 'city', 'photon-port'),
  ('port:port muhammad bin qasim|pakistan', 'Port Muhammad Bin Qasim', NULL, 'Pakistan', 24.7839, 67.3705, 'city', 'photon-port'),
  ('port:port natal|brazil', 'Port Natal', NULL, 'Brazil', -5.8054, -35.2081, 'city', 'photon-port'),
  ('port:port of spain|trinidad and tobago', 'Port Of Spain', NULL, 'Trinidad and Tobago', 10.6573, -61.5180, 'city', 'photon-port'),
  ('port:port said|egypt', 'Port Said', NULL, 'Egypt', 31.2632, 32.3055, 'city', 'photon-port'),
  ('port:portland, me', 'Portland', 'Maine', 'United States', 43.6351, -70.2543, 'city', 'photon-port'),
  ('port:portland, oregon', 'Portland', 'Oregon', 'United States', 45.6251, -122.7370, 'city', 'photon-port'),
  ('port:portland|australia', 'Portland', NULL, 'Australia', -38.3456, 141.6042, 'city', 'photon-port'),
  ('port:porto corsini|italy', 'Porto Corsini', NULL, 'Italy', 44.4938, 12.2769, 'city', 'photon-port'),
  ('port:porto de leixoes|portugal', 'Porto De Leixoes', NULL, 'Portugal', 41.1899, -8.6847, 'city', 'photon-port'),
  ('port:porto marghara|italy', 'Porto Marghara', NULL, 'Italy', 45.4724, 12.2559, 'city', 'photon-port'),
  ('port:prince rupert, bc|canada', 'Prince Rupert, Bc', NULL, 'Canada', 54.3127, -130.3255, 'city', 'photon-port'),
  ('port:progreso|mexico', 'Progreso', NULL, 'Mexico', 21.2822, -89.6637, 'city', 'photon-port'),
  ('port:providence, r.i.', 'Providence', 'Rhode Island', 'United States', 41.8240, -71.4128, 'city', 'photon-port'),
  ('port:pt. everglades, florida', 'Port Everglades', 'Florida', 'United States', 25.3679, -80.8783, 'city', 'photon-port'),
  ('port:pto. cayo grande de moa|cuba', 'Pto. Cayo Grande De Moa', NULL, 'Cuba', 20.6560, -74.9430, 'city', 'photon-port'),
  ('port:puerto barrios|guatemala', 'Puerto Barrios', NULL, 'Guatemala', 15.7275, -88.5953, 'city', 'photon-port'),
  ('port:puerto bolivar|ecuador', 'Puerto Bolivar', NULL, 'Ecuador', -0.0886, -76.1409, 'city', 'photon-port'),
  ('port:puerto cortes|honduras', 'Puerto Cortes', NULL, 'Honduras', 15.8515, -87.9427, 'city', 'photon-port'),
  ('port:puerto de la luz|spain', 'Puerto De La Luz', NULL, 'Spain', 28.1289, -15.4349, 'city', 'photon-port'),
  ('port:puerto henecan|honduras', 'Puerto Henecan', NULL, 'Honduras', 13.4213, -87.4487, 'city', 'photon-port'),
  ('port:puerto libertador|mexico', 'Puerto Libertador', NULL, 'Mexico', 22.5630, -98.1165, 'city', 'photon-port'),
  ('port:puerto libre de puerto mexico|mexico', 'Puerto Libre De Puerto Mexico', NULL, 'Mexico', 18.1405, -94.4344, 'city', 'photon-port'),
  ('port:puerto limon|costa rica', 'Puerto Limon', NULL, 'Costa Rica', 9.9900, -83.0303, 'city', 'photon-port'),
  ('port:puerto madero|mexico', 'Puerto Madero', NULL, 'Mexico', 14.7106, -92.4292, 'city', 'photon-port'),
  ('port:puerto manzanillo|mexico', 'Puerto Manzanillo', NULL, 'Mexico', 19.0506, -104.3160, 'city', 'photon-port'),
  ('port:puerto plata|dominican republic', 'Puerto Plata', NULL, 'Dominican Republic', 19.7892, -70.6926, 'city', 'photon-port'),
  ('port:puerto quetzal|guatemala', 'Puerto Quetzal', NULL, 'Guatemala', 13.9552, -90.7911, 'city', 'photon-port'),
  ('port:pursan|turkey', 'Pursan', NULL, 'Turkey', 40.1826, 29.0675, 'city', 'photon-port'),
  ('port:pusan|south korea', 'Pusan', NULL, 'South Korea', 35.1800, 129.0752, 'city', 'photon-port'),
  ('port:pyungtaek|south korea', 'Pyungtaek', NULL, 'South Korea', 36.9925, 127.1127, 'city', 'photon-port'),
  ('port:qingdao|china', 'Qingdao', NULL, 'China', 36.0663, 120.3778, 'city', 'photon-port'),
  ('port:qinhuangdao gang|china', 'Qinhuangdao Gang', NULL, 'China', 39.9368, 119.5942, 'city', 'photon-port'),
  ('port:rada di vado|italy', 'Rada Di Vado', NULL, 'Italy', 44.2714, 8.4382, 'city', 'photon-port'),
  ('port:rauma|finland', 'Rauma', NULL, 'Finland', 61.1289, 21.5039, 'city', 'photon-port'),
  ('port:reykjavik|iceland', 'Reykjavik', NULL, 'Iceland', 64.1460, -21.9422, 'city', 'photon-port'),
  ('port:richard''s bay|south africa', 'Richard''S Bay', NULL, 'South Africa', -28.7708, 32.0578, 'city', 'photon-port'),
  ('port:richmond, ca', 'Richmond', 'California', 'United States', 37.7867, -122.4948, 'city', 'photon-port'),
  ('port:ringaskiddy|ireland', 'Ringaskiddy', NULL, 'Ireland', 51.8328, -8.3053, 'city', 'photon-port'),
  ('port:rio de janeiro|brazil', 'Rio De Janeiro', NULL, 'Brazil', -22.9110, -43.2094, 'city', 'photon-port'),
  ('port:rio grande|brazil', 'Rio Grande', NULL, 'Brazil', -25.8598, -51.7005, 'city', 'photon-port'),
  ('port:rio jaina|dominican republic', 'Rio Jaina', NULL, 'Dominican Republic', 18.4322, -70.0310, 'city', 'photon-port'),
  ('port:road town, tortola island|british virgin islands', 'Road Town, Tortola Island', NULL, 'British Virgin Islands', 18.4258, -64.6231, 'city', 'photon-port'),
  ('port:rotterdam|netherlands', 'Rotterdam', NULL, 'Netherlands', 51.9244, 4.4778, 'city', 'photon-port'),
  ('port:sabine, texas', 'Sabine', 'Texas', 'United States', 31.3325, -93.8722, 'city', 'photon-port'),
  ('port:saint john, nb|canada', 'Saint John, Nb', NULL, 'Canada', 45.2788, -66.0585, 'city', 'photon-port'),
  ('port:salerno|italy', 'Salerno', NULL, 'Italy', 40.4194, 15.3106, 'city', 'photon-port'),
  ('port:salt lake city, utah', 'Salt Lake City', 'Utah', 'United States', 40.7516, -111.8897, 'city', 'photon-port'),
  ('port:salvador|brazil', 'Salvador', NULL, 'Brazil', -12.9822, -38.4813, 'city', 'photon-port'),
  ('port:san antonio|chile', 'San Antonio', NULL, 'Chile', -33.5809, -71.6132, 'city', 'photon-port'),
  ('port:san diego, ca', 'San Diego', 'California', 'United States', 32.5420, -117.0361, 'city', 'photon-port'),
  ('port:san juan, puerto rico', 'San Juan', 'Puerto Rico', 'United States', 18.4239, -66.0665, 'city', 'photon-port'),
  ('port:sangi|philippines', 'Sangi', NULL, 'Philippines', 14.7850, 120.2340, 'city', 'photon-port'),
  ('port:santander|spain', 'Santander', NULL, 'Spain', 43.4619, -3.8100, 'city', 'photon-port'),
  ('port:santo domingo|dominican republic', 'Santo Domingo', NULL, 'Dominican Republic', 18.4714, -69.8918, 'city', 'photon-port'),
  ('port:santo tomas de castilla|guatemala', 'Santo Tomas De Castilla', NULL, 'Guatemala', 15.6866, -88.6118, 'city', 'photon-port'),
  ('port:sao francisco do sul|brazil', 'Sao Francisco Do Sul', NULL, 'Brazil', -26.2495, -48.6308, 'city', 'photon-port'),
  ('port:sao paulo|brazil', 'Sao Paulo', NULL, 'Brazil', -22.0703, -48.4334, 'city', 'photon-port'),
  ('port:sault ste. marie, ont|canada', 'Sault Ste. Marie, Ont', NULL, 'Canada', 46.5127, -84.3330, 'city', 'photon-port'),
  ('port:saupe|brazil', 'Saupe', NULL, 'Brazil', -8.3539, -34.9567, 'city', 'photon-port'),
  ('port:savannah, ga', 'Savannah', 'Georgia', 'United States', 32.1266, -81.1450, 'city', 'photon-port'),
  ('port:savannah, ga.', 'Savannah', 'Georgia', 'United States', 32.1266, -81.1450, 'city', 'photon-port'),
  ('port:savona|italy', 'Savona', NULL, 'Italy', 44.2334, 8.2526, 'city', 'photon-port'),
  ('port:seal sands|united kingdom', 'Seal Sands', NULL, 'United Kingdom', 54.6114, -1.1742, 'city', 'photon-port'),
  ('port:seattle, wa', 'Seattle', 'Washington', 'United States', 47.5801, -122.3273, 'city', 'photon-port'),
  ('port:seattle, wash', 'Seattle', 'Washington', 'United States', 47.5801, -122.3273, 'city', 'photon-port'),
  ('port:semarang|indonesia', 'Semarang', NULL, 'Indonesia', -6.9904, 110.4229, 'city', 'photon-port'),
  ('port:sendai|japan', 'Sendai', NULL, 'Japan', 38.2678, 140.8691, 'city', 'photon-port'),
  ('port:setubal|portugal', 'Setubal', NULL, 'Portugal', 38.5242, -8.8932, 'city', 'photon-port'),
  ('port:shanghai|china', 'Shanghai', NULL, 'China', 31.2313, 121.4700, 'city', 'photon-port'),
  ('port:shantou, shan tou, san tou|china', 'Shantou, Shan Tou, San Tou', NULL, 'China', 23.3564, 116.6776, 'city', 'photon-port'),
  ('port:shekou|china', 'Shekou', NULL, 'China', 22.4910, 113.9225, 'city', 'photon-port'),
  ('port:shellhaven|united kingdom', 'Shellhaven', NULL, 'United Kingdom', 51.5138, 0.4252, 'city', 'photon-port'),
  ('port:shimizu|japan', 'Shimizu', NULL, 'Japan', 35.0991, 138.9027, 'city', 'photon-port'),
  ('port:sines|portugal', 'Sines', NULL, 'Portugal', 37.9565, -8.8690, 'city', 'photon-port'),
  ('port:singapore|singapore', 'Singapore', NULL, 'Singapore', 1.3571, 103.8195, 'city', 'photon-port'),
  ('port:soerabaya|indonesia', 'Soerabaya', NULL, 'Indonesia', -7.2463, 112.7378, 'city', 'photon-port'),
  ('port:songkhla harbor|thailand', 'Songkhla Harbor', NULL, 'Thailand', 7.1973, 100.5932, 'city', 'photon-port'),
  ('port:sorel, que|canada', 'Sorel, Que', NULL, 'Canada', 46.0435, -73.1165, 'city', 'photon-port'),
  ('port:southampton|united kingdom', 'Southampton', NULL, 'United Kingdom', 50.9025, -1.4042, 'city', 'photon-port'),
  ('port:sri racha|thailand', 'Sri Racha', NULL, 'Thailand', 13.1675, 100.9281, 'city', 'photon-port'),
  ('port:st. maarten|netherlands', 'St. Maarten', NULL, 'Netherlands', 18.0424, -63.0550, 'city', 'photon-port'),
  ('port:stadersand|germany', 'Stadersand', NULL, 'Germany', 53.5998, 9.4754, 'city', 'photon-port'),
  ('port:stockton, ca', 'Stockton', 'California', 'United States', 37.9893, -121.3224, 'city', 'photon-port'),
  ('port:susaka|croatia', 'Susaka', NULL, 'Croatia', 45.3268, 14.4422, 'city', 'photon-port'),
  ('port:sydney|australia', 'Sydney', NULL, 'Australia', -33.8698, 151.2083, 'city', 'photon-port'),
  ('port:tacoma, wa', 'Tacoma', 'Washington', 'United States', 47.2069, -122.5035, 'city', 'photon-port'),
  ('port:tacoma, wash', 'Tacoma', 'Washington', 'United States', 47.2069, -122.5035, 'city', 'photon-port'),
  ('port:tai chung|taiwan', 'Tai Chung', NULL, 'Taiwan', 24.1632, 120.6478, 'city', 'photon-port'),
  ('port:taicang|china', 'Taicang', NULL, 'China', 31.4590, 121.1265, 'city', 'photon-port'),
  ('port:taipei|taiwan', 'Taipei', NULL, 'Taiwan', 25.0375, 121.5637, 'city', 'photon-port'),
  ('port:tallinn|estonia', 'Tallinn', NULL, 'Estonia', 59.4372, 24.7573, 'city', 'photon-port'),
  ('port:tampa, fla', 'Tampa', 'Florida', 'United States', 27.9919, -82.5218, 'city', 'photon-port'),
  ('port:tampa, fla.', 'Tampa', 'Florida', 'United States', 27.9919, -82.5218, 'city', 'photon-port'),
  ('port:tamsui|taiwan', 'Tamsui', NULL, 'Taiwan', 25.1813, 121.4531, 'city', 'photon-port'),
  ('port:tan cang|vietnam', 'Tan Cang', NULL, 'Vietnam', 10.7987, 106.7233, 'city', 'photon-port'),
  ('port:tangier|morocco', 'Tangier', NULL, 'Morocco', 35.7696, -5.8034, 'city', 'photon-port'),
  ('port:tanjung pelepas|malaysia', 'Tanjung Pelepas', NULL, 'Malaysia', 1.3552, 103.5542, 'city', 'photon-port'),
  ('port:tanjung priok|indonesia', 'Tanjung Priok', NULL, 'Indonesia', -6.1338, 106.8737, 'city', 'photon-port'),
  ('port:tauranga|new zealand', 'Tauranga', NULL, 'New Zealand', -37.6859, 176.1675, 'city', 'photon-port'),
  ('port:texas city, texas', 'Texas City', 'Texas', 'United States', 31.8927, -102.3414, 'city', 'photon-port'),
  ('port:thanh pho ho chi minh|vietnam', 'Thanh Pho Ho Chi Minh', NULL, 'Vietnam', 10.7737, 106.7166, 'city', 'photon-port'),
  ('port:thessaloniki|greece', 'Thessaloniki', NULL, 'Greece', 40.6403, 22.9353, 'city', 'photon-port'),
  ('port:tianjin|china', 'Tianjin', NULL, 'China', 39.0844, 117.1957, 'city', 'photon-port'),
  ('port:tilbury|united kingdom', 'Tilbury', NULL, 'United Kingdom', 51.4616, 0.3637, 'city', 'photon-port'),
  ('port:toamasina|madagascar', 'Toamasina', NULL, 'Madagascar', -18.1554, 49.4098, 'city', 'photon-port'),
  ('port:tokuyama|japan', 'Tokuyama', NULL, 'Japan', 34.0551, 131.8064, 'city', 'photon-port'),
  ('port:tokyo|japan', 'Tokyo', NULL, 'Japan', 35.6769, 139.7639, 'city', 'photon-port'),
  ('port:tourane|vietnam', 'Tourane', NULL, 'Vietnam', 16.0680, 108.2120, 'city', 'photon-port'),
  ('port:toyohashi|japan', 'Toyohashi', NULL, 'Japan', 34.7691, 137.3915, 'city', 'photon-port'),
  ('port:tunis|tunisia', 'Tunis', NULL, 'Tunisia', 36.8002, 10.1858, 'city', 'photon-port'),
  ('port:tutunciftlik|turkey', 'Tutunciftlik', NULL, 'Turkey', 40.7524, 29.7883, 'city', 'photon-port'),
  ('port:tuxpan|mexico', 'Tuxpan', NULL, 'Mexico', 20.9298, -97.3937, 'city', 'photon-port'),
  ('port:ulsan|south korea', 'Ulsan', NULL, 'South Korea', 35.5392, 129.3119, 'city', 'photon-port'),
  ('port:valencia|spain', 'Valencia', NULL, 'Spain', 39.4697, -0.3763, 'city', 'photon-port'),
  ('port:valletta|malta', 'Valletta', NULL, 'Malta', 35.8990, 14.5137, 'city', 'photon-port'),
  ('port:vancouver, bc, canada', 'Bc', NULL, 'United States', 49.2609, -123.1140, 'city', 'photon-port'),
  ('port:vancouver, wash.', 'Vancouver', 'Washington', 'United States', 45.6569, -122.5903, 'city', 'photon-port'),
  ('port:veracruz|mexico', 'Veracruz', NULL, 'Mexico', 19.3333, -96.6667, 'city', 'photon-port'),
  ('port:victoria|brazil', 'Victoria', NULL, 'Brazil', -22.0344, -56.6106, 'city', 'photon-port'),
  ('port:vila do conde|brazil', 'Vila Do Conde', NULL, 'Brazil', -1.5679, -48.7583, 'city', 'photon-port'),
  ('port:vila real de san antonio|portugal', 'Vila Real De San Antonio', NULL, 'Portugal', 37.1946, -7.4156, 'city', 'photon-port'),
  ('port:vlissingen|netherlands', 'Vlissingen', NULL, 'Netherlands', 51.4481, 3.5698, 'city', 'photon-port'),
  ('port:vung tau|vietnam', 'Vung Tau', NULL, 'Vietnam', 10.3763, 107.0962, 'city', 'photon-port'),
  ('port:wellington|new zealand', 'Wellington', NULL, 'New Zealand', -41.2888, 174.7772, 'city', 'photon-port'),
  ('port:west palm beach, fla.', 'West Palm Beach', 'Florida', 'United States', 26.7154, -80.0533, 'city', 'photon-port'),
  ('port:wilhelmshaven|germany', 'Wilhelmshaven', NULL, 'Germany', 53.5279, 8.1063, 'city', 'photon-port'),
  ('port:wilmington, del.', 'Wilmington', 'Delaware', 'United States', 39.7459, -75.5466, 'city', 'photon-port'),
  ('port:wilmington, n.c.', 'Wilmington', 'North Carolina', 'United States', 34.1446, -77.8971, 'city', 'photon-port'),
  ('port:wilmington, nc', 'Wilmington', 'North Carolina', 'United States', 34.1446, -77.8971, 'city', 'photon-port'),
  ('port:xiamen|china', 'Xiamen', NULL, 'China', 24.4801, 118.0853, 'city', 'photon-port'),
  ('port:yangon|myanmar', 'Yangon', NULL, 'Myanmar', 16.7967, 96.1610, 'city', 'photon-port'),
  ('port:yangshan|china', 'Yangshan', NULL, 'China', 30.6220, 122.0693, 'city', 'photon-port'),
  ('port:yantian|china', 'Yantian', NULL, 'China', 22.5591, 114.2324, 'city', 'photon-port'),
  ('port:yarraville|australia', 'Yarraville', NULL, 'Australia', -37.8123, 144.8833, 'city', 'photon-port'),
  ('port:yentai|china', 'Yentai', NULL, 'China', 37.4619, 121.4425, 'city', 'photon-port'),
  ('port:yokohama|japan', 'Yokohama', NULL, 'Japan', 35.4503, 139.6344, 'city', 'photon-port'),
  ('port:zeebrugge|belgium', 'Zeebrugge', NULL, 'Belgium', 51.3312, 3.2076, 'city', 'photon-port'),
  ('port:zhongshan|china', 'Zhongshan', NULL, 'China', 22.5197, 113.3872, 'city', 'photon-port')
on conflict (place_key) do update set
  city = excluded.city,
  region = excluded.region,
  country = excluded.country,
  lat = excluded.lat,
  lng = excluded.lng,
  "precision" = excluded."precision",
  source = excluded.source;
