-- Phase 4 — click tracking
-- Phase 5 — A/B subject lines
--
-- Two non-overlapping additions in one migration so the dispatcher
-- redeploy that adopts both can land together.
--
-- Click tracking (Phase 4):
--   - lit_outreach_links — one row per (campaign_step, recipient, URL)
--     created at send time. Each row gets a short opaque slug. The
--     redirect-click edge function looks up the slug, records the
--     click, advances the recipient to status='clicked', then 302's
--     to the original URL.
--
-- A/B subject (Phase 5):
--   - lit_campaign_steps gains optional subject_b. When non-null, the
--     dispatcher picks A or B 50/50 per recipient and records the
--     choice in lit_outreach_history.metadata for later analytics.

-- ─── Phase 4: link + click tracking ──────────────────────────────────────────
create table if not exists public.lit_outreach_links (
  id                  uuid primary key default gen_random_uuid(),
  org_id              uuid references public.organizations(id) on delete cascade,
  user_id             uuid references auth.users(id) on delete set null,
  campaign_id         uuid references public.lit_campaigns(id) on delete cascade,
  campaign_step_id    uuid references public.lit_campaign_steps(id) on delete set null,
  recipient_id        uuid references public.lit_campaign_contacts(id) on delete set null,
  -- The short opaque slug embedded in the rewritten URL.
  -- Format: 12 base32 chars, generated by the dispatcher with
  -- crypto.getRandomValues. Globally unique.
  slug                text not null unique,
  -- The original URL the email body referenced.
  original_url        text not null,
  -- Aggregate metrics. Updated by the redirect endpoint.
  click_count         integer not null default 0,
  first_clicked_at    timestamptz,
  last_clicked_at     timestamptz,
  -- For UTM-style provenance + future audit.
  context             jsonb not null default '{}'::jsonb,
  created_at          timestamptz not null default now()
);

create index if not exists lit_outreach_links_recipient_idx
  on public.lit_outreach_links (recipient_id);
create index if not exists lit_outreach_links_campaign_idx
  on public.lit_outreach_links (campaign_id);
-- Note: no GIN/text-search index on original_url; lookup is always by slug.

alter table public.lit_outreach_links enable row level security;

-- Org members read; only service role writes (dispatcher + redirect endpoint).
drop policy if exists lit_outreach_links_select on public.lit_outreach_links;
create policy lit_outreach_links_select on public.lit_outreach_links
  for select using (
    org_id in (select org_id from public.org_members where user_id = auth.uid())
  );
-- (No insert/update policy = service-role only via Supabase.)

comment on table public.lit_outreach_links is
  'One row per tracked link in an outbound email. Slug is the opaque token in the rewritten URL; redirect-click records clicks and 302s to original_url.';

-- ─── Phase 5: A/B subject lines ──────────────────────────────────────────────
-- Optional alternate subject. Dispatcher picks A or B uniformly at random
-- per recipient when subject_b is not null. The chosen variant is recorded
-- in lit_outreach_history.metadata.{ab_variant: 'A'|'B'} so per-variant
-- open/click/reply rates can be computed downstream.
alter table public.lit_campaign_steps
  add column if not exists subject_b text;

comment on column public.lit_campaign_steps.subject_b is
  'Optional alternate subject line. Dispatcher picks A or B uniformly at random per recipient when present.';
