// Affiliate ref-code capture + persistence.
//
// Flow:
//   1. captureRefFromUrl()  — call on EVERY page load. Reads `?ref=<code>`
//      from the URL (any path, any subdomain). If present + valid, stashes
//      in localStorage AND a cookie with a 90-day TTL. Returns the code or
//      null. Idempotent — re-writing the same code just refreshes the TTL.
//   2. getStoredRef()  — read whichever store has the freshest ref. Returns
//      null when missing or older than 90 days.
//   3. clearStoredRef()  — after a successful claim, remove both stores.
//
// Storage redundancy: localStorage is fast + per-origin; cookie survives
// OAuth subdomain bounces (the Google/Microsoft redirect drops localStorage
// state). Either alone misses cases; both gives us a belt-and-suspenders
// capture that holds across a 2-3 month conversion window.

const STORAGE_KEY = "lit.affiliate_ref";
const COOKIE_NAME = "lit_affiliate_ref";
const TTL_MS = 90 * 24 * 60 * 60 * 1000; // 90 days

// Ref codes generated by accept-affiliate-invite are 6-12 char base32.
// Be permissive but reject obvious bad inputs.
const REF_CODE_PATTERN = /^[A-Za-z0-9_-]{4,32}$/;

type StoredRef = {
  code: string;
  captured_at: number; // epoch ms
  source_url: string;
};

function readCookie(name: string): string | null {
  if (typeof document === "undefined") return null;
  const match = document.cookie.match(
    new RegExp(`(?:^|;\\s*)${name}=([^;]*)`),
  );
  if (!match) return null;
  try {
    return decodeURIComponent(match[1]);
  } catch {
    return null;
  }
}

// Resolve the parent-domain cookie scope so a ref captured on
// logisticintel.com is readable from app.logisticintel.com (and vice
// versa). On localhost or any non-logisticintel host we leave Domain
// unset, scoping to the current host only.
function cookieDomainAttr(): string {
  if (typeof window === "undefined") return "";
  const host = window.location.hostname;
  if (!host) return "";
  // Match *.logisticintel.com (and the apex). Leading-dot Domain= shares
  // the cookie across all subdomains per RFC 6265bis.
  if (host === "logisticintel.com" || host.endsWith(".logisticintel.com")) {
    return "Domain=.logisticintel.com";
  }
  return "";
}

function writeCookie(name: string, value: string, maxAgeSeconds: number) {
  if (typeof document === "undefined") return;
  const secure = typeof window !== "undefined" && window.location.protocol === "https:";
  const parts = [
    `${name}=${encodeURIComponent(value)}`,
    "Path=/",
    `Max-Age=${maxAgeSeconds}`,
    "SameSite=Lax",
  ];
  const domain = cookieDomainAttr();
  if (domain) parts.push(domain);
  if (secure) parts.push("Secure");
  document.cookie = parts.join("; ");
}

function deleteCookie(name: string) {
  if (typeof document === "undefined") return;
  // Wipe both scopes: parent-domain (shared) and the current host (default).
  const domain = cookieDomainAttr();
  document.cookie = `${name}=; Path=/; Max-Age=0; SameSite=Lax${domain ? "; " + domain : ""}`;
  document.cookie = `${name}=; Path=/; Max-Age=0; SameSite=Lax`;
}

/**
 * Read `?ref=<code>` from the current URL and persist it. Called on app
 * mount and on every route change. Returns the captured code or null.
 */
export function captureRefFromUrl(): string | null {
  if (typeof window === "undefined") return null;
  try {
    const params = new URLSearchParams(window.location.search);
    const raw = (params.get("ref") || params.get("aff") || params.get("partner") || "").trim();
    if (!raw) return null;
    if (!REF_CODE_PATTERN.test(raw)) return null;

    const payload: StoredRef = {
      code: raw,
      captured_at: Date.now(),
      source_url: window.location.href,
    };
    try {
      window.localStorage.setItem(STORAGE_KEY, JSON.stringify(payload));
    } catch {
      // private mode / quota — cookie still covers us
    }
    writeCookie(COOKIE_NAME, raw, Math.floor(TTL_MS / 1000));
    return raw;
  } catch {
    return null;
  }
}

/**
 * Return the persisted ref code if still within the 90-day window, else
 * null. Prefers localStorage (richer metadata); falls back to cookie.
 */
export function getStoredRef(): string | null {
  if (typeof window === "undefined") return null;
  try {
    const raw = window.localStorage.getItem(STORAGE_KEY);
    if (raw) {
      const parsed = JSON.parse(raw) as StoredRef;
      if (parsed?.code && typeof parsed.captured_at === "number") {
        const age = Date.now() - parsed.captured_at;
        if (age <= TTL_MS) return parsed.code;
        // Stale — clear it. Cookie path below may still hit, refresh if so.
        window.localStorage.removeItem(STORAGE_KEY);
      }
    }
  } catch {
    // ignore parse errors
  }
  const fromCookie = readCookie(COOKIE_NAME);
  if (fromCookie && REF_CODE_PATTERN.test(fromCookie)) return fromCookie;
  return null;
}

/**
 * Clear both stores. Call after the server confirms the referral has been
 * recorded — avoids double-attribution on subsequent sessions.
 */
export function clearStoredRef() {
  try {
    if (typeof window !== "undefined") window.localStorage.removeItem(STORAGE_KEY);
  } catch {}
  deleteCookie(COOKIE_NAME);
}
