name: Deploy Hosting (frontend/firebase.json)
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install deps
        working-directory: frontend
        run: npm ci

      - name: Build
        working-directory: frontend
        env:
          VITE_PROXY_BASE: /api/public
        run: npm run build

      - name: Authenticate to Google Cloud (OIDC)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/187580267283/locations/global/workloadIdentityPools/github/providers/github
          service_account: github-actions-deployer@logistics-intel.iam.gserviceaccount.com
          create_credentials_file: true
          export_environment_variables: true

      - name: Deploy to Firebase Hosting
        working-directory: frontend
        run: npx --yes firebase-tools deploy --only hosting --project logistics-intel --config firebase.json --non-interactive --force
