name: Deploy Hosting
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install deps
        working-directory: frontend
        run: pnpm install --frozen-lockfile

      - name: Build
        working-directory: frontend
        env:
          VITE_PROXY_BASE: /api/public
        run: pnpm build

      - name: Authenticate to Google Cloud (OIDC)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/187580267283/locations/global/workloadIdentityPools/github/providers/github
          service_account: github-actions-deployer@logistics-intel.iam.gserviceaccount.com
          export_default_credentials: true

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Deploy to Firebase Hosting
        working-directory: frontend
        run: firebase deploy --only hosting --project logistics-intel --non-interactive --force
