name: Deploy Functions
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/functions/package-lock.json

      - name: Authenticate to Google Cloud (OIDC)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/187580267283/locations/global/workloadIdentityPools/github/providers/github
          service_account: github-actions-deployer@logistics-intel.iam.gserviceaccount.com
          create_credentials_file: true
          export_environment_variables: true

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Install function dependencies
        working-directory: frontend/functions
        run: npm ci

      - name: Deploy callable function
        working-directory: frontend
        run: firebase deploy --only functions:searchCompanies_index --project logistics-intel --non-interactive --force
